#ifndef ERROR_CODE_DEFS_H
#define ERROR_CODE_DEFS_H
/*
#define NO_ERROR        0
#define NORMAL_FAILED   -1

enum EnErrorCode
{	
	ERROR_LOGIN_NEED_AUTH_CODE=1,
	ERROR_WRONG_USERNAME,
	ERROR_WRONG_PASSWORD,
	ERROR_WRONG_VERSION,
	ERROR_ESERVICELOGIN,
	ERROR_BLACKUSER,
	ERROR_MOBILENO_LOGINERROR,
	ERROR_NEED_SECURITYLOGIN,				//需要二次登陆
	ERROR_NO_FIRST_LOGIN,					//没有首次登陆
	ERROR_TOKENVALIDATE_FAILED,				//token校验失败
	ERROR_USERLIST_FAILED,					//取联系人列表失败
};


enum EnAddContactErrorCode
{
	ADD_CONTACT_OK = 0,						//添加成功
	ADD_CONTACT_ADDED,
	ADD_CONTACT_NOID,
	ADD_CONTACT_FULL,
	ADD_CONTACT_FULLTODAY,
	ADD_CONTACT_NEED_AUTH_WORDS,
	ADD_CONTACT_NORIGHT,
	ADD_CONTACT_NOTACTIVEID,
	ADD_CONTACT_PEER_DENY_ALL,
	ADD_CONTACT_PEER_DENY,					//对方拒绝, 这种情况下，接口可能会返回对方拒绝你时想对你说的话ß
	ADD_CONTACT_FAILED
};	
*/
#endif //ERROR_CODE_DEFS_H
