/*
 * AMSocketTypes.h
 *
 *  Created on: 2009-11-23
 *      Author: qinghua.liqh
 */
#ifndef _AM_SOCKET_TYPES_H_
#define _AM_SOCKET_TYPES_H_

/*
WindowsSockets错误码	Berkeley 对应错误码	错误号			解释
WSAEINTR				EINTR				10004			同标准C
WSAEBADF				EBADF				10009			同标准C
WSAEACCES				EACCES				10013			同标准C
WSAEFAULT				EFAULT				10014			同标准C
WSAEINVAL				EINVAL				10022			同标准C
WSAEMFILE				EMFILE				10024			同标准C
WSAEWOULDBLOCK			EWOULDBLOCK			10035			同BSD
WSAEINPROGRESS			EINPROGRESS			10036			当一个阻塞函数正在进行时，调用任何Windows Sockets API函数均返回此错误
WSAEALREADY				EALREADY			10037			同BSD
WSAENOTSOCK				ENOTSOCK			10038			同BSD
WSAEDESTADDRREQ			EDESTADDRREQ		10039			同BSD
WSAEMSGSIZE				EMSGSIZE			10040			同BSD
WSAEPROTOTYPE			EPROTOTYPE			10041			同BSD
WSAENOPROTOOPT			ENOPROTOOPT			10042			同BSD
WSAEPROTONOSUPPORT		EPROTONOSUPPORT		10043			同BSD
WSAESOCKTNOSUPPORT		ESOCKTNOSUPPORT		10044			同BSD
WSAEOPNOTSUPP			EOPNOTSUPP			10045			同BSD
WSAEPFNOSUPPORT			EPFNOSUPPORT		10046			同BSD
WSAEAFNOSUPPORT			EAFNOSUPPORT		10047			同BSD
WSAEADDRINUSE			EADDRINUSE			10048			同BSD
WSAEADDRNOTAVAIL		EADDRNOTAVAIL		10049			同BSD
WSAENETDOWN				ENETDOWN			10050			同BSD。任何时候只要Windows Sockets实现检测到网络子系统失败，它就报告此错误。
WSAENETUNREACH			ENETUNREACH			10051			同BSD
WSAENETRESET			ENETRESET			10052			同BSD
WSAECONNABORTED			ECONNABORTED		10053			同BSD
WSAECONNRESET			ECONNRESET			10054			同BSD
WSAENOBUFS				ENOBUFS				10055			同BSD
WSAEISCONN				EISCONN				10056			同BSD
WSAENOTCONN				ENOTCONN			10057			同BSD
WSAESHUTDOWN			ESHUTDOWN			10058			同BSD
WSAETOOMANYREFS			ETOOMANYREFS		10059			同BSD
WSAETIMEDOUT			ETIMEDOUT			10060			同BSD
WSAECONNREFUSED			ECONNREFUSED		10061			同BSD
WSAELOOP				ELOOP				10062			同BSD
WSAENAMETOOLONG			ENAMETOOLONG		10063			同BSD
WSAEHOSTDOWN			EHOSTDOWN			10064			同BSD
WSAEHOSTUNREACH			EHOSTUNREACH		10065			同BSD
WSASYSNOTREADY								10091			由WSAStartup() 返回，指示网络子系统无法使用。
WSAVERNOTSUPPORTED							10092			由WSAStartup() 返回，指示Windows Sockets
															DLL 不能支持此应用程序。
WSANOTINITIALISED							10093			由除WSAStartup()之外的其它函数返回，指示 尚没有一次成功的WSAStartup() 调用执行过。
WSAEDISCON									10101			由WSARecv()和WSARecvFrom()返回，指示远程方已经初始化了一个“雅致”的shutdown序列。
WSAHOST_NOT_FOUND		HOST_NOT_FOUND		11001			同BSD
WSATRY_AGAIN			TRY_AGAIN			11002			同BSD
WSANO_RECOVERY			NO_RECOVERY			11003			同BSD
WSANO_DATA				NO_DATA				11004			同BSD
*/

#if (defined (_WIN32_WCE) || defined(_WIN32)) && (!defined(__SYMBIAN32__)) 		//windows, wince.
/*
#define		WSAEINTR			10004
#define		WSAEBADF			10009
#define		WSAEACCES			10013
#define		WSAEFAULT			10014
#define		WSAEINVAL			10022
#define		WSAEMFILE			10024
#define		WSAEWOULDBLOCK		10035
#define		WSAEINPROGRESS		10036
#define		WSAEALREADY			10037
#define		WSAENOTSOCK			10038
#define		WSAEDESTADDRREQ		10039
#define		WSAEMSGSIZE			10040
#define		WSAEPROTOTYPE		10041
#define		WSAENOPROTOOPT		10042
#define		WSAEPROTONOSUPPORT	10043
#define		WSAESOCKTNOSUPPORT	10044
#define		WSAEOPNOTSUPP		10045
#define		WSAEPFNOSUPPORT		10046
#define		WSAEAFNOSUPPORT		10047
#define		WSAEADDRINUSE		10048
#define		WSAEADDRNOTAVAIL	10049
#define		WSAENETDOWN			10050
#define		WSAENETUNREACH		10051
#define		WSAENETRESET		10052
#define		WSAECONNABORTED		10053
#define		WSAECONNRESET		10054
#define		WSAENOBUFS			10055
#define		WSAEISCONN			10056
#define		WSAENOTCONN			10057
#define		WSAESHUTDOWN		10058
#define		WSAETOOMANYREFS		10059
#define		WSAETIMEDOUT		10060
#define		WSAECONNREFUSED		10061
#define		WSAELOOP			10062
#define		WSAENAMETOOLONG		10063
#define		WSAEHOSTDOWN		10064
#define		WSAEHOSTUNREACH		10065
#define		WSASYSNOTREADY		10091
#define		WSAVERNOTSUPPORTED	10092
#define		WSANOTINITIALISED	10093
#define		WSAEDISCON			10101
#define		WSAHOST_NOT_FOUND	11001
#define		WSATRY_AGAIN		11002
#define		WSANO_RECOVERY		11003
#define		WSANO_DATA			11004
*/

#define	NET_EINTR				WSAEINTR
#define	NET_EBADF				WSAEBADF
#define	NET_EACCES				WSAEACCES
#define	NET_EFAULT				WSAEFAULT
#define	NET_EINVAL				WSAEINVAL
#define	NET_EMFILE				WSAEMFILE
#define	NET_EWOULDBLOCK			WSAEWOULDBLOCK
#define	NET_EINPROGRESS			WSAEINPROGRESS
#define	NET_EALREADY			WSAEALREADY
#define	NET_ENOTSOCK			WSAENOTSOCK
#define	NET_EDESTADDRREQ		WSAEDESTADDRREQ
#define	NET_EMSGSIZE			WSAEMSGSIZE
#define	NET_EPROTOTYPE			WSAEPROTOTYPE
#define	NET_ENOPROTOOPT			WSAENOPROTOOPT
#define	NET_EPROTONOSUPPORT		WSAEPROTONOSUPPORT
#define	NET_ESOCKTNOSUPPORT		WSAESOCKTNOSUPPORT
#define	NET_EOPNOTSUPP			WSAEOPNOTSUPP
#define	NET_EPFNOSUPPORT		WSAEPFNOSUPPORT
#define	NET_EAFNOSUPPORT		WSAEAFNOSUPPORT
#define	NET_EADDRINUSE			WSAEADDRINUSE
#define	NET_EADDRNOTAVAIL		WSAEADDRNOTAVAIL
#define	NET_ENETDOWN			WSAENETDOWN
#define	NET_ENETUNREACH			WSAENETUNREACH
#define	NET_ENETRESET			WSAENETRESET
#define	NET_ECONNABORTED		WSAECONNABORTED
#define	NET_ECONNRESET			WSAECONNRESET
#define	NET_ENOBUFS				WSAENOBUFS
#define	NET_EISCONN				WSAEISCONN
#define	NET_ENOTCONN			WSAENOTCONN
#define	NET_ESHUTDOWN			WSAESHUTDOWN
#define	NET_ETOOMANYREFS		WSAETOOMANYREFS
#define	NET_ETIMEDOUT			WSAETIMEDOUT
#define	NET_ECONNREFUSED		WSAECONNREFUSED
#define	NET_ELOOP				WSAELOOP
#define	NET_ENAMETOOLONG		WSAENAMETOOLONG
#define	NET_EHOSTDOWN			WSAEHOSTDOWN
#define	NET_EHOSTUNREACH		WSAEHOSTUNREACH
//#define					WSASYSNOTREADY
//#define					WSAVERNOTSUPPORTED
//#define					WSANOTINITIALISED
//#define					WSAEDISCON
#define	NET_HOST_NOT_FOUND		WSAHOST_NOT_FOUND
#define	NET_TRY_AGAIN			WSATRY_AGAIN
#define	NET_NO_RECOVERY			WSANO_RECOVERY
#define	NET_NO_DATA				WSANO_DATA
#else
#define	NET_EINTR				4
#define	NET_EBADF				9
#define	NET_EACCES				13
#define	NET_EFAULT				14
#define	NET_EINVAL				22
#define	NET_EMFILE				24
#define	NET_EWOULDBLOCK			11
#define	NET_EINPROGRESS			119
#define	NET_EALREADY			120
#define	NET_ENOTSOCK			108
#define	NET_EDESTADDRREQ		121
#define	NET_EMSGSIZE			122
#define	NET_EPROTOTYPE			107
#define	NET_ENOPROTOOPT			109
#define	NET_EPROTONOSUPPORT		123
#define	NET_ESOCKTNOSUPPORT		124
#define	NET_EOPNOTSUPP			95
#define	NET_EPFNOSUPPORT		96
#define	NET_EAFNOSUPPORT		106
#define	NET_EADDRINUSE			112
#define	NET_EADDRNOTAVAIL		125
#define	NET_ENETDOWN			115
#define	NET_ENETUNREACH			114
#define	NET_ENETRESET			126
#define	NET_ECONNABORTED		113
#define	NET_ECONNRESET			104
#define	NET_ENOBUFS				105
#define	NET_EISCONN				127
#define	NET_ENOTCONN			128
#define	NET_ESHUTDOWN			110
#define	NET_ETOOMANYREFS		129
#define	NET_ETIMEDOUT			116
#define	NET_ECONNREFUSED		111
#define	NET_ELOOP				92
#define	NET_ENAMETOOLONG		91
#define	NET_EHOSTDOWN			117
#define	NET_EHOSTUNREACH		118
//#define					0
//#define					0
//#define					0
//#define					0
#define	NET_HOST_NOT_FOUND		0
#define	NET_TRY_AGAIN			0
#define	NET_NO_RECOVERY			0
#define	NET_NO_DATA				0
#define	NET_NO_DATA				0		
#endif
#define ERROR_COMMON		    -1
#endif //_AM_SOCKET_TYPES_H_
