/* DO NOT EDIT THIS FILE - it is machine generated */

#if defined(TARGET_VMKIT)
#include "vos_inc/jni.h"
#else
#include <jni.h>
#endif // TARGET_VMKIT

/* Header for class com_alibaba_wireless_imservice_ConnectionAdapter */

#ifndef _Included_com_alibaba_wireless_imservice_ConnectionAdapter
#define _Included_com_alibaba_wireless_imservice_ConnectionAdapter
#ifdef __cplusplus
extern "C" {
#endif
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_registerConnectionListener
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_registerConnectionListener 1L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_registerContactListListener
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_registerContactListListener 2L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_registerPresenceListener
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_registerPresenceListener 3L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_registerChatSessionListener
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_registerChatSessionListener 4L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_unregisterConnectionListener
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_unregisterConnectionListener 5L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_unregisterContactListListener
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_unregisterContactListListener 6L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_unregisterPresenceListener
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_unregisterPresenceListener 7L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_unregisterChatSessionListener
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_unregisterChatSessionListener 8L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_getOwner
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_getOwner 9L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_getStatus
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_getStatus 10L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_login
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_login 11L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_logout
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_logout 12L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_cancel
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_cancel 13L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_getCurrentAccount
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_getCurrentAccount 14L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_getCurrentToken
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_getCurrentToken 15L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_getCurrentWebMD5
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_getCurrentWebMD5 16L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_getAllGroupList
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_getAllGroupList 17L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_getContactList
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_getContactList 18L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_getRecentContactList
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_getRecentContactList 19L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_getBlackList
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_getBlackList 20L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_changeStatus
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_changeStatus 21L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_changeSignature
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_changeSignature 22L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_chgServerMode
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_chgServerMode 23L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_sendMessage
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_sendMessage 24L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_removeAllMessage
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_removeAllMessage 25L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_addContact
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_addContact 26L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_removeContact
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_removeContact 27L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_sendVerifyInfo
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_sendVerifyInfo 28L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_rejectAddContact
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_rejectAddContact 29L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_acceptAddContact
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_acceptAddContact 30L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_changeVerifyType
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_changeVerifyType 31L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_removeRecent
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_removeRecent 32L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_removeStranger
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_removeStranger 33L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_addBlack
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_addBlack 34L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_removeBlack
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_removeBlack 35L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_getContactVerify
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_getContactVerify 36L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_getContactUDBProfile
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_getContactUDBProfile 37L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_getContactPortrait
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_getContactPortrait 38L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_getContactSignature
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_getContactSignature 39L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_getChatSession
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_getChatSession 40L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_getChatSessions
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_getChatSessions 41L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_getFastReplyList
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_getFastReplyList 42L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_removeFastReply
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_removeFastReply 43L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_addFastReply
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_addFastReply 44L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_modifyFastReply
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_modifyFastReply 45L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_getGroupCnt
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_getGroupCnt 46L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_getGroupOnlineCnt
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_getGroupOnlineCnt 47L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_getUnreadMsgCnt
#define com_alibaba_wireless_imservice_ConnectionAdapter_TRANSACTION_getUnreadMsgCnt 48L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_STATUS_INVALID
#define com_alibaba_wireless_imservice_ConnectionAdapter_STATUS_INVALID -1L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_STATUS_EXEMPT
#define com_alibaba_wireless_imservice_ConnectionAdapter_STATUS_EXEMPT -2L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_STATUS_IDEL
#define com_alibaba_wireless_imservice_ConnectionAdapter_STATUS_IDEL 1L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_STATUS_NETOK
#define com_alibaba_wireless_imservice_ConnectionAdapter_STATUS_NETOK 2L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_STATUS_NETPUZZLE
#define com_alibaba_wireless_imservice_ConnectionAdapter_STATUS_NETPUZZLE 3L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_STATUS_LOGINOK
#define com_alibaba_wireless_imservice_ConnectionAdapter_STATUS_LOGINOK 4L
#undef com_alibaba_wireless_imservice_ConnectionAdapter_STATUS_DATAREADY
#define com_alibaba_wireless_imservice_ConnectionAdapter_STATUS_DATAREADY 5L
	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nRegisterListener
	* Signature: (I)I
	*/
	JNIEXPORT jint JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nRegisterListener
		(JNIEnv *, jobject, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetCurrentAccount
	* Signature: (I)I
	*/
	JNIEXPORT jint JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetCurrentAccount
		(JNIEnv *, jobject, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nLogin
	* Signature: (I[B[BZIZZZZ)V
	*/
	JNIEXPORT void JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nLogin
		(JNIEnv *, jobject, jint, jbyteArray, jbyteArray, jboolean, jint, jboolean, jboolean, jboolean, jboolean);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nLoginEx
	* Signature: (I[B[BZIZZZZ[B)V
	*/
	JNIEXPORT void JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nLoginEx
		(JNIEnv *, jobject, jint, jbyteArray, jbyteArray, jboolean, jint, jboolean, jboolean, jboolean, jboolean, jbyteArray);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nLogout
	* Signature: (I)V
	*/
	JNIEXPORT void JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nLogout
		(JNIEnv *, jobject, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nRemoveBlack
	* Signature: (I[B)V
	*/
	JNIEXPORT void JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nRemoveBlack
		(JNIEnv *, jobject, jint, jbyteArray);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nAddBlack
	* Signature: (I[B)V
	*/
	JNIEXPORT void JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nAddBlack
		(JNIEnv *, jobject, jint, jbyteArray);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nAddContact
	* Signature: (I[B)V
	*/
	JNIEXPORT void JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nAddContact
		(JNIEnv *, jobject, jint, jbyteArray);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nRemoveContact
	* Signature: (I[B)V
	*/
	JNIEXPORT void JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nRemoveContact
		(JNIEnv *, jobject, jint, jbyteArray);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nChangeStatus
	* Signature: (II)V
	*/
	JNIEXPORT void JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nChangeStatus
		(JNIEnv *, jobject, jint, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nChangeVerifyType
	* Signature: (II)V
	*/
	JNIEXPORT void JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nChangeVerifyType
		(JNIEnv *, jobject, jint, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nAcceptAddContact
	* Signature: (I[B)V
	*/
	JNIEXPORT void JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nAcceptAddContact
		(JNIEnv *, jobject, jint, jbyteArray);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nRejectAddContact
	* Signature: (I[B[B)V
	*/
	JNIEXPORT void JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nRejectAddContact
		(JNIEnv *, jobject, jint, jbyteArray, jbyteArray);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nSendMessage
	* Signature: (I[B[B)V
	*/
	JNIEXPORT void JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nSendMessage
		(JNIEnv *, jobject, jint, jbyteArray, jbyteArray);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nSendMessageEx
	* Signature: (I[B[BI)V
	*/
	JNIEXPORT void JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nSendMessageEx
		(JNIEnv *, jobject, jint, jbyteArray, jbyteArray, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nSendU2UMessage
	* Signature: (I[B[BI)V
	*/
	JNIEXPORT void JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nSendU2UMessage
		(JNIEnv *, jobject, jint, jbyteArray, jbyteArray, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nSendVerifyInfo
	* Signature: (I[B[B[B)V
	*/
	JNIEXPORT void JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nSendVerifyInfo
		(JNIEnv *, jobject, jint, jbyteArray, jbyteArray, jbyteArray);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetAccounts
	* Signature: (I)[I
	*/
	JNIEXPORT jintArray JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetAccounts
		(JNIEnv *, jobject, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetBlackList
	* Signature: (I)[I
	*/
	JNIEXPORT jintArray JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetBlackList
		(JNIEnv *, jobject, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetRecentList
	* Signature: (I)[I
	*/
	JNIEXPORT jintArray JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetRecentList
		(JNIEnv *, jobject, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetChatSession
	* Signature: (I[BZ)I
	*/
	JNIEXPORT jint JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetChatSession
		(JNIEnv *, jobject, jint, jbyteArray, jboolean);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nAddFastReply
	* Signature: (I[B)J
	*/
	JNIEXPORT jlong JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nAddFastReply
		(JNIEnv *, jobject, jint, jbyteArray);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetFastReplyList
	* Signature: (I)[I
	*/
	JNIEXPORT jintArray JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetFastReplyList
		(JNIEnv *, jobject, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nModifyFastReply
	* Signature: (IJ[B)V
	*/
	JNIEXPORT void JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nModifyFastReply
		(JNIEnv *, jobject, jint, jlong, jbyteArray);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nRemoveFastReply
	* Signature: (IJ)V
	*/
	JNIEXPORT void JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nRemoveFastReply
		(JNIEnv *, jobject, jint, jlong);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nChgServerMode
	* Signature: (IZ)V
	*/
	JNIEXPORT void JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nChgServerMode
		(JNIEnv *, jobject, jint, jboolean);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nRemoveRecentContact
	* Signature: (I[B)V
	*/
	JNIEXPORT void JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nRemoveRecentContact
		(JNIEnv *, jobject, jint, jbyteArray);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nRemoveAllMessage
	* Signature: (I)I
	*/
	JNIEXPORT jint JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nRemoveAllMessage
		(JNIEnv *, jobject, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetTopGroupHandles
	* Signature: (I)[I
	*/
	JNIEXPORT jintArray JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetTopGroupHandles
		(JNIEnv *, jobject, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nCloseChatSession
	* Signature: (II)I
	*/
	JNIEXPORT jint JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nCloseChatSession
		(JNIEnv *, jobject, jint, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nRemoveStrangerContact
	* Signature: (I[B)V
	*/
	JNIEXPORT void JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nRemoveStrangerContact
		(JNIEnv *, jobject, jint, jbyteArray);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nCancel
	* Signature: (I)V
	*/
	JNIEXPORT void JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nCancel
		(JNIEnv *, jobject, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetImStatus
	* Signature: (I)I
	*/
	JNIEXPORT jint JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetImStatus
		(JNIEnv *, jobject, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetCurrentToken
	* Signature: (I)[B
	*/
	JNIEXPORT jbyteArray JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetCurrentToken
		(JNIEnv *, jobject, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetCurrentWebMD5
	* Signature: (I)[B
	*/
	JNIEXPORT jbyteArray JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetCurrentWebMD5
		(JNIEnv *, jobject, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetContactVerify
	* Signature: (I[BI)V
	*/
	JNIEXPORT void JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetContactVerify
		(JNIEnv *, jobject, jint, jbyteArray, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetContactUDBProfile
	* Signature: (I[B)V
	*/
	JNIEXPORT void JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetContactUDBProfile
		(JNIEnv *, jobject, jint, jbyteArray);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetContactPortrait
	* Signature: (I[B)V
	*/
	JNIEXPORT void JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetContactPortrait
		(JNIEnv *, jobject, jint, jbyteArray);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nChangeSignature
	* Signature: (I[B)V
	*/
	JNIEXPORT void JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nChangeSignature
		(JNIEnv *, jobject, jint, jbyteArray);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetContactSignature
	* Signature: (I[BI)V
	*/
	JNIEXPORT void JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetContactSignature
		(JNIEnv *, jobject, jint, jbyteArray, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetAcntHandle
	* Signature: (I[B)I
	*/
	JNIEXPORT jint JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetAcntHandle
		(JNIEnv *, jclass, jint, jbyteArray);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetAcntID
	* Signature: (I)[B
	*/
	JNIEXPORT jbyteArray JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetAcntID
		(JNIEnv *, jclass, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetAcntName
	* Signature: (I)[B
	*/
	JNIEXPORT jbyteArray JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetAcntName
		(JNIEnv *, jclass, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetAcntType
	* Signature: (I)I
	*/
	JNIEXPORT jint JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetAcntType
		(JNIEnv *, jclass, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetAcntStatus
	* Signature: (I)I
	*/
	JNIEXPORT jint JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetAcntStatus
		(JNIEnv *, jclass, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetAcntFlag
	* Signature: (I)I
	*/
	JNIEXPORT jint JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetAcntFlag
		(JNIEnv *, jclass, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetAcntPhone
	* Signature: (I)[B
	*/
	JNIEXPORT jbyteArray JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetAcntPhone
		(JNIEnv *, jclass, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nIsPwdNull
	* Signature: (I)Z
	*/
	JNIEXPORT jboolean JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nIsPwdNull
		(JNIEnv *, jclass, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetGrpHandle
	* Signature: (IJ)I
	*/
	JNIEXPORT jint JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetGrpHandle
		(JNIEnv *, jclass, jint, jlong);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetGrpID
	* Signature: (I)J
	*/
	JNIEXPORT jlong JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetGrpID
		(JNIEnv *, jclass, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetGrpName
	* Signature: (I)[B
	*/
	JNIEXPORT jbyteArray JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetGrpName
		(JNIEnv *, jclass, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetCntList
	* Signature: (I)[I
	*/
	JNIEXPORT jintArray JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetCntList
		(JNIEnv *, jclass, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetGrpList
	* Signature: (I)[I
	*/
	JNIEXPORT jintArray JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetGrpList
		(JNIEnv *, jclass, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetCntNum
	* Signature: (I)I
	*/
	JNIEXPORT jint JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetCntNum
		(JNIEnv *, jclass, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetOnlineNum
	* Signature: (I)I
	*/
	JNIEXPORT jint JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetOnlineNum
		(JNIEnv *, jclass, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetParentGrp
	* Signature: (I)I
	*/
	JNIEXPORT jint JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetParentGrp
		(JNIEnv *, jclass, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetUnreadMsgCnt
	* Signature: (I)I
	*/
	JNIEXPORT jint JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetUnreadMsgCnt
		(JNIEnv *, jclass, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetCntHandle
	* Signature: (I[B)I
	*/
	JNIEXPORT jint JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetCntHandle
		(JNIEnv *, jclass, jint, jbyteArray);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    ngetCntGrpID
	* Signature: (I)J
	*/
	JNIEXPORT jlong JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_ngetCntGrpID
		(JNIEnv *, jclass, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetCntID
	* Signature: (I)[B
	*/
	JNIEXPORT jbyteArray JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetCntID
		(JNIEnv *, jclass, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetCntType
	* Signature: (I)I
	*/
	JNIEXPORT jint JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetCntType
		(JNIEnv *, jclass, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetCntNick
	* Signature: (I)[B
	*/
	JNIEXPORT jbyteArray JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetCntNick
		(JNIEnv *, jclass, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetCntPinyin
	* Signature: (I)[B
	*/
	JNIEXPORT jbyteArray JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetCntPinyin
		(JNIEnv *, jclass, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetCntLastMsg
	* Signature: (I)[B
	*/
	JNIEXPORT jbyteArray JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetCntLastMsg
		(JNIEnv *, jclass, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetCntStatus
	* Signature: (I)I
	*/
	JNIEXPORT jint JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetCntStatus
		(JNIEnv *, jclass, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetCntParentGrp
	* Signature: (I)I
	*/
	JNIEXPORT jint JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetCntParentGrp
		(JNIEnv *, jclass, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetCntFlag
	* Signature: (I)I
	*/
	JNIEXPORT jint JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetCntFlag
		(JNIEnv *, jclass, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetSignature
	* Signature: (I)[B
	*/
	JNIEXPORT jbyteArray JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetSignature
		(JNIEnv *, jclass, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetPhoneNum
	* Signature: (I)[B
	*/
	JNIEXPORT jbyteArray JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetPhoneNum
		(JNIEnv *, jclass, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nUnregisterListener
	* Signature: (I)I
	*/
	JNIEXPORT jint JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nUnregisterListener
		(JNIEnv *, jobject, jint);

	/*
 * Class:     com_alibaba_wireless_imservice_ConnectionAdapter
 * Method:    nMsgGetCntId
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nMsgGetCntId
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_alibaba_wireless_imservice_ConnectionAdapter
 * Method:    nMsgGetBody
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nMsgGetBody
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_alibaba_wireless_imservice_ConnectionAdapter
 * Method:    nMsgGetId
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nMsgGetId
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_alibaba_wireless_imservice_ConnectionAdapter
 * Method:    nMsgGetType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nMsgGetType
  (JNIEnv *, jclass, jint);

/*
* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
* Method:    nMsgGetU2UType
* Signature: (I)I
*/
JNIEXPORT jint JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nMsgGetU2UType
(JNIEnv *, jclass, jint);

/*
 * Class:     com_alibaba_wireless_imservice_ConnectionAdapter
 * Method:    nMsgGetTime
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nMsgGetTime
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_alibaba_wireless_imservice_ConnectionAdapter
 * Method:    nMsgGetUnread
 * Signature: (I)B
 */
JNIEXPORT jbyte JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nMsgGetUnread
  (JNIEnv *, jclass, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nSetMobileImMessage
	* Signature: ([B)V
	*/
	JNIEXPORT void JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nSetMobileImMessage
		(JNIEnv *, jclass, jbyteArray);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nSetTtid
	* Signature: ([B)V
	*/
	JNIEXPORT void JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nSetTtid
		(JNIEnv *, jclass, jbyteArray);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetOperationMessage
	* Signature: (I)[B
	*/
	JNIEXPORT jbyteArray JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetOperationMessage
		(JNIEnv *, jclass, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetCurSigXML
	* Signature: (I)[B
	*/
	JNIEXPORT jbyteArray JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetCurSigXML
		(JNIEnv *env, jobject obj, jint handle);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nUpdateSetting
	* Signature: (IIZZZ)I
	*/
	JNIEXPORT jint JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nUpdateSetting
		(JNIEnv *, jobject , jint , jint , jboolean, jboolean , jboolean);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nBlockStranger
	* Signature: (IIZ)I
	*/
	JNIEXPORT jint JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nBlockStranger
		(JNIEnv *env, jobject obj, jint iHandle, jboolean bBlockStranger);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nSendFile
	* Signature: (I[B[B)I
	*/
	JNIEXPORT jint JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nSendFile
		(JNIEnv *env, jobject obj, jint iHandle, jbyteArray contantID, jbyteArray filePath);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nReceiveFile
	* Signature: (I[B[B[B)I
	*/
	JNIEXPORT jint JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nReceiveFile
		(JNIEnv *env, jobject obj, jint iHandle, jbyteArray contantID, jbyteArray objXml, jbyteArray filePath);


	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nCancelTrans
	* Signature: (II)I
	*/
	JNIEXPORT jint JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nCancelTrans
		(JNIEnv *env, jobject obj, jint iHandle, jint iTaskId);

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nCheckAuth
	* Signature: (II[B)I
	*/
	JNIEXPORT jint JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nCheckAuth
		(JNIEnv *env, jobject obj, jint iHandle, jint iAuthId, jbyteArray jbCode);
	
	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nUpdateAuth
	* Signature: (II)I
	*/
	JNIEXPORT jint JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nUpdateAuth
		(JNIEnv *env, jobject obj, jint iHandle, jint iAuthId);
	
	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nCancelAuth
	* Signature: (II)I
	*/
	JNIEXPORT jint JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nCancelAuth
		(JNIEnv *env, jobject obj, jint iHandle, jint iAuthId);

	
	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nReLogin
	* Signature: (I)I
	*/
	JNIEXPORT jint JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nReLogin
		(JNIEnv *env, jobject obj, jint iHandle);

	
	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetRemarkMsg
	* Signature: ()[B
	*/
	JNIEXPORT jbyteArray JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetRemarkMsg
		(JNIEnv *env, jobject obj, jint iHandle);
	
	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetWebSession
	* Signature: ()[B
	*/
	JNIEXPORT jbyteArray JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetWebSession
		(JNIEnv *env, jobject obj, jint iHandle) ;

	/*
	* Class:     com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:    nGetCurrentPhoneNum
	* Signature: ()[B
	*/
	JNIEXPORT jbyteArray JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nGetCurrentPhoneNum
		(JNIEnv *env, jobject obj, jint iHandle) ;


	/*
	* Class:	 com_alibaba_wireless_imservice_ConnectionAdapter
	* Method:	 nSearchUser
	* Signature: (I[B)V
	*/
	JNIEXPORT jbyteArray JNICALL Java_com_alibaba_wireless_imservice_ConnectionAdapter_nSearchUser
		(JNIEnv *, jobject, jint, jbyteArray);



#ifdef __cplusplus
}
#endif
#endif
