/* DO NOT EDIT THIS FILE - it is machine generated */
#if defined(TARGET_VMKIT)
#include "vos_inc/jni.h"
#else
#include <jni.h>
#endif // TARGET_VMKIT
/* Header for class com_alibaba_wireless_imservice_IMService */

#ifndef _Included_com_alibaba_wireless_imservice_IMService
#define _Included_com_alibaba_wireless_imservice_IMService
#ifdef __cplusplus
extern "C" {
#endif


JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *jvm, void *reserved);

/*
* Class:     com_alibaba_wireless_imservice_IMService
* Method:    native_SetDatabasePath
* Signature: ([B)V
*/
JNIEXPORT void JNICALL Java_com_alibaba_wireless_imservice_IMService_native_1SetDatabasePath
(JNIEnv *, jclass, jbyteArray);

/*
* Class:     com_alibaba_wireless_imservice_IMService
* Method:    native_IAccountModel_Create
* Signature: ()I
*/
JNIEXPORT jint JNICALL Java_com_alibaba_wireless_imservice_IMService_native_1IAccountModel_1Create
(JNIEnv *, jclass);

/*
* Class:     com_alibaba_wireless_imservice_IMService
* Method:    native_IAccountModel_Destroy
* Signature: (I)V
*/
JNIEXPORT void JNICALL Java_com_alibaba_wireless_imservice_IMService_native_1IAccountModel_1Destroy
(JNIEnv *, jclass, jint);

/*
 * Class:     com_alibaba_wireless_imservice_IMService
 * Method:    native_IAIM_Create
 * Signature: ()I
 */

JNIEXPORT jint JNICALL Java_com_alibaba_wireless_imservice_IMService_native_1IAIM_1Create
  (JNIEnv *, jclass);

/*
 * Class:     com_alibaba_wireless_imservice_IMService
 * Method:    native_IAIM_Destroy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_alibaba_wireless_imservice_IMService_native_1IAIM_1Destroy
  (JNIEnv *, jclass, jint);

/*
* Class:     com_alibaba_wireless_imservice_IMService
* Method:    nGetAccountHandles
* Signature: (I)[I
*/
JNIEXPORT jintArray JNICALL Java_com_alibaba_wireless_imservice_IMService_nGetAccountHandles
(JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
