/* DO NOT EDIT THIS FILE - it is machine generated */
#if defined(TARGET_VMKIT)
#include "vos_inc/jni.h"
#else
#include <jni.h>
#endif // TARGET_VMKIT

/* Header for class com_alibaba_wireless_imservice_ChatSession */

#ifndef _Included_com_alibaba_wireless_imservice_ChatSession
#define _Included_com_alibaba_wireless_imservice_ChatSession
#ifdef __cplusplus
extern "C" {
#endif
#undef com_alibaba_wireless_imservice_ChatSession_TRANSACTION_getContactId
#define com_alibaba_wireless_imservice_ChatSession_TRANSACTION_getContactId 1L
#undef com_alibaba_wireless_imservice_ChatSession_TRANSACTION_sendMessage
#define com_alibaba_wireless_imservice_ChatSession_TRANSACTION_sendMessage 2L
#undef com_alibaba_wireless_imservice_ChatSession_TRANSACTION_leave
#define com_alibaba_wireless_imservice_ChatSession_TRANSACTION_leave 3L
#undef com_alibaba_wireless_imservice_ChatSession_TRANSACTION_getHistoryMsgCount
#define com_alibaba_wireless_imservice_ChatSession_TRANSACTION_getHistoryMsgCount 4L
#undef com_alibaba_wireless_imservice_ChatSession_TRANSACTION_getHistoryMsg
#define com_alibaba_wireless_imservice_ChatSession_TRANSACTION_getHistoryMsg 5L
#undef com_alibaba_wireless_imservice_ChatSession_TRANSACTION_getUnreadMsgCount
#define com_alibaba_wireless_imservice_ChatSession_TRANSACTION_getUnreadMsgCount 6L
#undef com_alibaba_wireless_imservice_ChatSession_TRANSACTION_getUnreadMsg
#define com_alibaba_wireless_imservice_ChatSession_TRANSACTION_getUnreadMsg 7L
#undef com_alibaba_wireless_imservice_ChatSession_TRANSACTION_markMessageRead
#define com_alibaba_wireless_imservice_ChatSession_TRANSACTION_markMessageRead 8L
#undef com_alibaba_wireless_imservice_ChatSession_TRANSACTION_removeMessage
#define com_alibaba_wireless_imservice_ChatSession_TRANSACTION_removeMessage 9L
	/*
	* Class:     com_alibaba_wireless_imservice_ChatSession
	* Method:    nGetContactId
	* Signature: (I)[B
	*/
	JNIEXPORT jbyteArray JNICALL Java_com_alibaba_wireless_imservice_ChatSession_nGetContactId
		(JNIEnv *, jclass, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ChatSession
	* Method:    nSendMsg
	* Signature: (I[B)V
	*/
	JNIEXPORT void JNICALL Java_com_alibaba_wireless_imservice_ChatSession_nSendMsg
		(JNIEnv *, jclass, jint, jbyteArray);

	/*
	* Class:     com_alibaba_wireless_imservice_ChatSession
	* Method:    nSendMsgEx
	* Signature: (I[BI)V
	*/
	JNIEXPORT void JNICALL Java_com_alibaba_wireless_imservice_ChatSession_nSendMsgEx
		(JNIEnv *, jclass , jint , jbyteArray , jint );

	/*
	* Class:     com_alibaba_wireless_imservice_ChatSession
	* Method:    nLeave
	* Signature: (I)V
	*/
	JNIEXPORT void JNICALL Java_com_alibaba_wireless_imservice_ChatSession_nLeave
		(JNIEnv *, jclass, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ChatSession
	* Method:    nGetHistoryCount
	* Signature: (I)I
	*/
	JNIEXPORT jint JNICALL Java_com_alibaba_wireless_imservice_ChatSession_nGetHistoryCount
		(JNIEnv *, jclass, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ChatSession
	* Method:    nGetHistoryHandle
	* Signature: (IJI)[I
	*/
	JNIEXPORT jintArray JNICALL Java_com_alibaba_wireless_imservice_ChatSession_nGetHistoryHandle
		(JNIEnv *, jclass, jint, jlong, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ChatSession
	* Method:    nGetUnreadCount
	* Signature: (I)I
	*/
	JNIEXPORT jint JNICALL Java_com_alibaba_wireless_imservice_ChatSession_nGetUnreadCount
		(JNIEnv *, jclass, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ChatSession
	* Method:    nGetUnreadHandle
	* Signature: (III)[I
	*/
	JNIEXPORT jintArray JNICALL Java_com_alibaba_wireless_imservice_ChatSession_nGetUnreadHandle
		(JNIEnv *, jclass, jint, jint, jint);

	/*
	* Class:     com_alibaba_wireless_imservice_ChatSession
	* Method:    nMarkMessageRead
	* Signature: (IJ)V
	*/
	JNIEXPORT void JNICALL Java_com_alibaba_wireless_imservice_ChatSession_nMarkMessageRead
		(JNIEnv *, jclass, jint, jlong);

	/*
	* Class:     com_alibaba_wireless_imservice_ChatSession
	* Method:    nRemoveMessage
	* Signature: (IJ)V
	*/
	JNIEXPORT void JNICALL Java_com_alibaba_wireless_imservice_ChatSession_nRemoveMessage
		(JNIEnv *, jclass, jint, jlong);

	/*
	* Class:     com_alibaba_wireless_imservice_ChatSession
	* Method:    nReleaseMsgs
	* Signature: (I[I)V
	*/
	JNIEXPORT void JNICALL Java_com_alibaba_wireless_imservice_ChatSession_nReleaseMsgs
		(JNIEnv *, jclass, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
