#ifndef __AIMENUM_H__
#define __AIMENUM_H__

#include "AMTypes.h"

#define	AMHandle	AMPVoid

typedef enum AIM_ACCOUNT_TYPE
{		
	eAIM_ACNTYPE_TAOBAO		= 0,
	eAIM_ACNTYPE_ALICHN		= 1,
	eAIM_ACNTYPE_KOUBEI		= 2,
	eAIM_ACNTYPE_WANGWANG	= 3,
	eAIM_ACNTYPE_YAHOO		= 4,
	eAIM_ACNTYPE_ALIINT		= 5,
	eAIM_ACNTYPE_ANONYM		= 6,
	eAIM_ACNTYPE_ALIMAMA	= 7,
	eAIM_ACNTYPE_ALIYUN		= 8,

	eAIM_ACNTYPE_WRONG		= -1
}AIM_ACCOUNT_TYPE;

typedef enum AIM_RESULT
{
	eAIM_RESULT_OK				= 0,
	eAIM_RESULT_NOT_READY		= -0x100,
	eAIM_RESULT_MALLOC_ERROR,
	eAIM_RESULT_PARAM_ERROR,
	eAIM_RESULT_DB_ERROR,
	eAIM_RESULT_DUP,	//下载、上传重复
	eAIM_RESULT_FILE_OPEN,
	eAIM_RESULT_FILE_READ,
	eAIM_RESULT_FILE_CLOSE,
	eAIM_RESULT_CANCEL,		//被取消
	eAIM_RESULT_NET,
	eAIM_RESULT_NOT_SUPPORT,

	eAIM_RESULT_FAIL			= -1,
}AIM_RESULT;

typedef enum AIM_PRESENCE
{
	eAIM_PRESENCE_OFFLINE		= 0,
	eAIM_PRESENCE_ONLINE		= 1,
	eAIM_PRESENCE_BUSY			= 2,
	eAIM_PRESENCE_AWAY			= 3,
	eAIM_PRESENCE_ON_PHONE		= 4,
	eAIM_PRESENCE_OUT2LUNCH		= 5,
	eAIM_PRESENCE_RIGHT_BACK	= 6,
	eAIM_PRESENCE_INVISIBLE		= 7,
	eAIM_PRESENCE_OFF_LOGIN		= 8,
	eAIM_PRESENCE_UNKNOW		= 9,
	eAIM_PRESENCE_FAKE_ONLINE	= 10,
	eAIM_PRESENCE_NOT_USED		= 11,
	eAIM_PRESENCE_SMS			= 12,
	eAIM_PRESENCE_MOBILE		= 30,

	eAIM_PRESENCE_MOBILE_BASE		= 32,
	eAIM_PRESENCE_MOBILE_OFFLINE	= eAIM_PRESENCE_MOBILE_BASE,
	eAIM_PRESENCE_MOBILE_ONLINE,
	eAIM_PRESENCE_MOBILE_BUSY,
	eAIM_PRESENCE_MOBILE_AWAY,
	eAIM_PRESENCE_MOBILE_ON_PHONE,
	eAIM_PRESENCE_MOBILE_OUT2LUNCH,
	eAIM_PRESENCE_MOBILE_RIGHT_BACK,
	eAIM_PRESENCE_MOBILE_INVISIBLE,
	eAIM_PRESENCE_MOBILE_OFF_LOGIN,
	eAIM_PRESENCE_MOBILE_UNKNOW,

	eAIM_PRESENCE_WRONG			= -1,
}AIM_PRESENCE;

typedef struct AIM_ACCOUNT_SETTING
{
	AIM_PRESENCE	eDefaultPresence;
	AMBool			bSavePwd;
	AMBool			bMute;
	AMBool			bViberate;
} AIM_ACCOUNT_SETTING;

typedef enum AIM_BIND_STATUS
{
	eAIM_BIND_INIT		= 0,
	eAIM_BIND_GETING,
	eAIM_BIND_GET_BINDED_FAIL,
	eAIM_BIND_NO_BIND,
	eAIM_BIND_BINDED,
	eAIM_BIND_BIND_KICK,
}AIM_BIND_STATUS;

#endif