#include <string>

#include "StringConversionUtils.h"

#define _T(str) str
#define TCHAR char

const TCHAR* B0[] = {_T("a"), _T("a"), _T("ai"), _T("ai"), _T("ai"), _T("ai"), _T("ai"), _T("ai"), _T("ai"), _T("ai"), _T("ai"), _T("ai"), _T("ai"), _T("ai"), _T("ai"), _T("an"), _T("an"), _T("an"), _T("an"), _T("an"), _T("an"), _T("an"), _T("an"), _T("an"), _T("ang"), _T("ang"), _T("ang"), _T("ao"), _T("ao"), _T("ao"), _T("ao"), _T("ao"), _T("ao"), _T("ao"), _T("ao"), _T("ao"), _T("ba"), _T("ba"), _T("ba"), _T("ba"), _T("ba"), _T("ba"), _T("ba"), _T("ba"), _T("ba"), _T("ba"), _T("ba"), _T("ba"), _T("ba"), _T("ba"), _T("ba"), _T("ba"), _T("ba"), _T("ba"), _T("bai"), _T("bai"), _T("bai"), _T("bai"), _T("bai"), _T("bai"), _T("bai"), _T("bai"), _T("ban"), _T("ban"), _T("ban"), _T("ban"), _T("ban"), _T("ban"), _T("ban"), _T("ban"), _T("ban"), _T("ban"), _T("ban"), _T("ban"), _T("ban"), _T("ban"), _T("ban"), _T("bang"), _T("bang"), _T("bang"), _T("bang"), _T("bang"), _T("bang"), _T("bang"), _T("bang"), _T("bang"), _T("bang"), _T("bang"), _T("bang"), _T("bao"), _T("bao"), _T("bao"), _T("bao"), _T("bao"), NULL};
const TCHAR* B1[] = {_T("bao"), _T("bao"), _T("bao"), _T("bao"), _T("bao"), _T("bao"), _T("bao"), _T("bao"), _T("bao"), _T("bao"), _T("bao"), _T("bao"), _T("bei"), _T("bei"), _T("bei"), _T("bei"), _T("bei"), _T("bei"), _T("bei"), _T("bei"), _T("bei"), _T("bei"), _T("bei"), _T("bei"), _T("bei"), _T("bei"), _T("bei"), _T("ben"), _T("ben"), _T("ben"), _T("ben"), _T("beng"), _T("beng"), _T("beng"), _T("beng"), _T("beng"), _T("beng"), _T("bi"), _T("bi"), _T("bi"), _T("bi"), _T("bi"), _T("bi"), _T("bi"), _T("bi"), _T("bi"), _T("bi"), _T("bi"), _T("bi"), _T("bi"), _T("bi"), _T("bi"), _T("bi"), _T("bi"), _T("bi"), _T("bi"), _T("bi"), _T("bi"), _T("bei"), _T("bi"), _T("bi"), _T("bian"), _T("bian"), _T("bian"), _T("bian"), _T("bian"), _T("bian"), _T("bian"), _T("bian"), _T("bian"), _T("bian"), _T("bian"), _T("bian"), _T("biao"), _T("biao"), _T("biao"), _T("biao"), _T("bie"), _T("bie"), _T("bie"), _T("bie"), _T("bin"), _T("bin"), _T("bin"), _T("bin"), _T("bin"), _T("bin"), _T("bing"), _T("bing"), _T("bing"), _T("bing"), _T("bing"), _T("bing"), _T("bing"), NULL};
const TCHAR* B2[] = {_T("bing"), _T("bing"), _T("bo"), _T("bo"), _T("bo"), _T("bo"), _T("bo"), _T("bo"), _T("bo"), _T("bo"), _T("bo"), _T("bo"), _T("bo"), _T("bai"), _T("bo"), _T("bo"), _T("bo"), _T("bo"), _T("bo"), _T("bo"), _T("bo"), _T("bu"), _T("bo"), _T("bu"), _T("bu"), _T("bu"), _T("bu"), _T("bu"), _T("bu"), _T("bu"), _T("bu"), _T("bu"), _T("ca"), _T("cai"), _T("cai"), _T("cai"), _T("cai"), _T("cai"), _T("cai"), _T("cai"), _T("cai"), _T("cai"), _T("cai"), _T("cai"), _T("can"), _T("can"), _T("can"), _T("can"), _T("can"), _T("can"), _T("can"), _T("cang"), _T("cang"), _T("cang"), _T("cang"), _T("cang"), _T("cao"), _T("cao"), _T("cao"), _T("cao"), _T("cao"), _T("ce"), _T("ce"), _T("ce"), _T("ce"), _T("ce"), _T("ceng"), _T("ceng"), _T("cha"), _T("cha"), _T("cha"), _T("cha"), _T("cha"), _T("cha"), _T("cha"), _T("cha"), _T("cha"), _T("cha"), _T("cha"), _T("chai"), _T("chai"), _T("chai"), _T("chan"), _T("chan"), _T("chan"), _T("chan"), _T("chan"), _T("chan"), _T("chan"), _T("chan"), _T("chan"), _T("chan"), _T("chang"), _T("chang"), NULL};
const TCHAR* B3[] = {_T("chang"), _T("chang"), _T("chang"), _T("chang"), _T("chang"), _T("chang"), _T("chang"), _T("chang"), _T("chang"), _T("chang"), _T("chang"), _T("chao"), _T("chao"), _T("chao"), _T("chao"), _T("chao"), _T("chao"), _T("chao"), _T("chao"), _T("chao"), _T("che"), _T("che"), _T("che"), _T("che"), _T("che"), _T("che"), _T("chen"), _T("chen"), _T("chen"), _T("chen"), _T("chen"), _T("chen"), _T("chen"), _T("chen"), _T("chen"), _T("chen"), _T("cheng"), _T("chen"), _T("cheng"), _T("cheng"), _T("cheng"), _T("cheng"), _T("cheng"), _T("cheng"), _T("cheng"), _T("cheng"), _T("cheng"), _T("cheng"), _T("cheng"), _T("cheng"), _T("cheng"), _T("chi"), _T("chi"), _T("chi"), _T("chi"), _T("chi"), _T("chi"), _T("chi"), _T("chi"), _T("chi"), _T("chi"), _T("chi"), _T("chi"), _T("chi"), _T("chi"), _T("chi"), _T("chi"), _T("chong"), _T("chong"), _T("chong"), _T("chong"), _T("chong"), _T("chou"), _T("chou"), _T("chou"), _T("chou"), _T("chou"), _T("chou"), _T("chou"), _T("chou"), _T("chou"), _T("chou"), _T("chou"), _T("chou"), _T("chu"), _T("chu"), _T("chu"), _T("chu"), _T("chu"), _T("chu"), _T("chu"), _T("chu"), _T("chu"), _T("chu"), NULL};
const TCHAR* B4[] = {_T("chu"), _T("chu"), _T("chu"), _T("chu"), _T("chu"), _T("chu"), _T("chuai"), _T("chuan"), _T("chuan"), _T("chuan"), _T("chuan"), _T("chuan"), _T("chuan"), _T("chuan"), _T("chuang"), _T("chuang"), _T("chuang"), _T("chuang"), _T("chuang"), _T("chuang"), _T("chui"), _T("chui"), _T("chui"), _T("chui"), _T("chui"), _T("chun"), _T("chun"), _T("chun"), _T("chun"), _T("chun"), _T("chun"), _T("chun"), _T("chuo"), _T("chao"), _T("ci"), _T("ci"), _T("ci"), _T("ci"), _T("ci"), _T("ci"), _T("ci"), _T("ci"), _T("ci"), _T("ci"), _T("ci"), _T("ci"), _T("cong"), _T("cong"), _T("cong"), _T("cong"), _T("cong"), _T("cong"), _T("cou"), _T("cu"), _T("cu"), _T("cu"), _T("cu"), _T("cuan"), _T("cuan"), _T("cuan"), _T("cui"), _T("cui"), _T("cui"), _T("cui"), _T("cui"), _T("cui"), _T("cui"), _T("cui"), _T("cun"), _T("cun"), _T("cun"), _T("cuo"), _T("cuo"), _T("cuo"), _T("cuo"), _T("cuo"), _T("cuo"), _T("da"), _T("da"), _T("da"), _T("da"), _T("da"), _T("da"), _T("dai"), _T("dai"), _T("dai"), _T("dai"), _T("dai"), _T("dai"), _T("dai"), _T("dai"), _T("dai"), _T("dai"), _T("dai"), NULL};
const TCHAR* B5[] = {_T("dai"), _T("dan"), _T("dan"), _T("dan"), _T("chan"), _T("dan"), _T("dan"), _T("dan"), _T("dan"), _T("dan"), _T("dan"), _T("dan"), _T("dan"), _T("dan"), _T("dan"), _T("dan"), _T("dang"), _T("dang"), _T("dang"), _T("dang"), _T("dang"), _T("dao"), _T("dao"), _T("dao"), _T("dao"), _T("dao"), _T("dao"), _T("dao"), _T("dao"), _T("dao"), _T("dao"), _T("dao"), _T("dao"), _T("de"), _T("de"), _T("de"), _T("deng"), _T("deng"), _T("deng"), _T("deng"), _T("deng"), _T("deng"), _T("deng"), _T("di"), _T("di"), _T("di"), _T("di"), _T("di"), _T("di"), _T("di"), _T("di"), _T("di"), _T("di"), _T("di"), _T("di"), _T("de"), _T("di"), _T("di"), _T("di"), _T("di"), _T("di"), _T("di"), _T("dian"), _T("dian"), _T("dian"), _T("dian"), _T("dian"), _T("dian"), _T("dian"), _T("dian"), _T("dian"), _T("dian"), _T("dian"), _T("dian"), _T("dian"), _T("dian"), _T("dian"), _T("dian"), _T("diao"), _T("diao"), _T("diao"), _T("diao"), _T("diao"), _T("diao"), _T("diao"), _T("diao"), _T("diao"), _T("die"), _T("die"), _T("die"), _T("die"), _T("die"), _T("die"), _T("die"), NULL};
const TCHAR* B6[] = {_T("ding"), _T("ding"), _T("ding"), _T("ding"), _T("ding"), _T("ding"), _T("ding"), _T("ding"), _T("ding"), _T("diu"), _T("dong"), _T("dong"), _T("dong"), _T("dong"), _T("dong"), _T("dong"), _T("dong"), _T("dong"), _T("dong"), _T("dong"), _T("dou"), _T("dou"), _T("dou"), _T("dou"), _T("dou"), _T("dou"), _T("dou"), _T("dou"), _T("du"), _T("du"), _T("du"), _T("du"), _T("du"), _T("du"), _T("du"), _T("du"), _T("du"), _T("du"), _T("du"), _T("du"), _T("du"), _T("du"), _T("duan"), _T("duan"), _T("duan"), _T("duan"), _T("duan"), _T("duan"), _T("dui"), _T("dui"), _T("dui"), _T("dui"), _T("dun"), _T("dun"), _T("dun"), _T("dun"), _T("dun"), _T("dun"), _T("dun"), _T("dun"), _T("dun"), _T("duo"), _T("duo"), _T("duo"), _T("duo"), _T("duo"), _T("duo"), _T("duo"), _T("duo"), _T("duo"), _T("duo"), _T("duo"), _T("duo"), _T("e"), _T("e"), _T("e"), _T("e"), _T("e"), _T("e"), _T("e"), _T("e"), _T("e"), _T("e"), _T("e"), _T("e"), _T("e"), _T("en"), _T("er"), _T("er"), _T("er"), _T("er"), _T("er"), _T("er"), _T("er"), NULL};
const TCHAR* B7[] = {_T("er"), _T("fa"), _T("fa"), _T("fa"), _T("fa"), _T("fa"), _T("fa"), _T("fa"), _T("fa"), _T("fan"), _T("fan"), _T("fan"), _T("fan"), _T("fan"), _T("fan"), _T("fan"), _T("fan"), _T("fan"), _T("fan"), _T("fan"), _T("fan"), _T("fan"), _T("fan"), _T("fan"), _T("fan"), _T("fan"), _T("fang"), _T("fang"), _T("fang"), _T("fang"), _T("fang"), _T("fang"), _T("fang"), _T("fang"), _T("fang"), _T("fang"), _T("fang"), _T("fei"), _T("fei"), _T("fei"), _T("fei"), _T("fei"), _T("fei"), _T("fei"), _T("fei"), _T("fei"), _T("fei"), _T("fei"), _T("fei"), _T("fen"), _T("fen"), _T("fen"), _T("fen"), _T("fen"), _T("fen"), _T("fen"), _T("fen"), _T("fen"), _T("fen"), _T("fen"), _T("fen"), _T("fen"), _T("fen"), _T("fen"), _T("feng"), _T("feng"), _T("feng"), _T("feng"), _T("feng"), _T("feng"), _T("feng"), _T("feng"), _T("feng"), _T("feng"), _T("feng"), _T("feng"), _T("feng"), _T("feng"), _T("feng"), _T("fo"), _T("fou"), _T("fu"), _T("fu"), _T("fu"), _T("fu"), _T("fu"), _T("fu"), _T("fu"), _T("fu"), _T("fu"), _T("fu"), _T("fu"), _T("fu"), _T("fu"), NULL};
const TCHAR* B8[] = {_T("fu"), _T("fu"), _T("fu"), _T("fu"), _T("fu"), _T("fu"), _T("fu"), _T("fu"), _T("fu"), _T("fu"), _T("fu"), _T("fu"), _T("fu"), _T("fu"), _T("fu"), _T("fu"), _T("fu"), _T("fu"), _T("fu"), _T("fu"), _T("fu"), _T("fu"), _T("fu"), _T("fu"), _T("fu"), _T("fu"), _T("fu"), _T("fu"), _T("fu"), _T("fu"), _T("fu"), _T("fu"), _T("ga"), _T("ga"), _T("gai"), _T("gai"), _T("gai"), _T("gai"), _T("gai"), _T("gai"), _T("gan"), _T("gan"), _T("gan"), _T("gan"), _T("gan"), _T("gan"), _T("gan"), _T("gan"), _T("gan"), _T("gan"), _T("gan"), _T("gang"), _T("gang"), _T("gang"), _T("gang"), _T("gang"), _T("gang"), _T("gang"), _T("gang"), _T("gang"), _T("gao"), _T("gao"), _T("gao"), _T("gao"), _T("gao"), _T("gao"), _T("gao"), _T("gao"), _T("gao"), _T("gao"), _T("ge"), _T("ge"), _T("ge"), _T("ge"), _T("ge"), _T("ge"), _T("ge"), _T("ge"), _T("ge"), _T("ge"), _T("ge"), _T("ge"), _T("ge"), _T("ge"), _T("ge"), _T("ge"), _T("ge"), _T("gei"), _T("gen"), _T("gen"), _T("geng"), _T("geng"), _T("geng"), _T("geng"), NULL};
const TCHAR* B9[] = {_T("geng"), _T("geng"), _T("geng"), _T("gong"), _T("gong"), _T("gong"), _T("gong"), _T("gong"), _T("gong"), _T("gong"), _T("gong"), _T("gong"), _T("gong"), _T("gong"), _T("gong"), _T("gong"), _T("gong"), _T("gong"), _T("gou"), _T("gou"), _T("gou"), _T("gou"), _T("gou"), _T("gou"), _T("gou"), _T("gou"), _T("gou"), _T("gu"), _T("gu"), _T("gu"), _T("gu"), _T("gu"), _T("gu"), _T("gu"), _T("gu"), _T("gu"), _T("gu"), _T("gu"), _T("gu"), _T("gu"), _T("gu"), _T("gu"), _T("gu"), _T("gu"), _T("gu"), _T("gua"), _T("gua"), _T("gua"), _T("gua"), _T("gua"), _T("gua"), _T("guai"), _T("guai"), _T("guai"), _T("guan"), _T("guan"), _T("guan"), _T("guan"), _T("guan"), _T("guan"), _T("guan"), _T("guan"), _T("guan"), _T("guan"), _T("guan"), _T("guang"), _T("guang"), _T("guang"), _T("gui"), _T("gui"), _T("gui"), _T("gui"), _T("gui"), _T("gui"), _T("gui"), _T("gui"), _T("gui"), _T("gui"), _T("gui"), _T("gui"), _T("gui"), _T("gui"), _T("gui"), _T("gui"), _T("gun"), _T("gun"), _T("gun"), _T("guo"), _T("guo"), _T("guo"), _T("guo"), _T("guo"), _T("guo"), _T("ha"), NULL};
const TCHAR* BA[] = {_T("hai"), _T("hai"), _T("hai"), _T("hai"), _T("hai"), _T("hai"), _T("hai"), _T("han"), _T("han"), _T("han"), _T("han"), _T("han"), _T("han"), _T("han"), _T("han"), _T("han"), _T("han"), _T("han"), _T("han"), _T("han"), _T("han"), _T("han"), _T("han"), _T("han"), _T("han"), _T("han"), _T("hang"), _T("hang"), _T("hang"), _T("hao"), _T("hao"), _T("hao"), _T("hao"), _T("hao"), _T("hao"), _T("hao"), _T("hao"), _T("hao"), _T("he"), _T("he"), _T("he"), _T("he"), _T("he"), _T("he"), _T("he"), _T("he"), _T("ge"), _T("he"), _T("hao"), _T("he"), _T("he"), _T("he"), _T("he"), _T("he"), _T("he"), _T("he"), _T("hei"), _T("hei"), _T("hen"), _T("hen"), _T("hen"), _T("hen"), _T("heng"), _T("heng"), _T("heng"), _T("heng"), _T("heng"), _T("hong"), _T("hong"), _T("hong"), _T("hong"), _T("hong"), _T("hong"), _T("hong"), _T("hong"), _T("hong"), _T("hou"), _T("hou"), _T("hou"), _T("hou"), _T("hou"), _T("hou"), _T("hou"), _T("hu"), _T("hu"), _T("hu"), _T("hu"), _T("hu"), _T("hu"), _T("hu"), _T("hu"), _T("hu"), _T("hu"), _T("hu"), NULL};
const TCHAR* BB[] = {_T("hu"), _T("hu"), _T("hu"), _T("hu"), _T("hu"), _T("hu"), _T("hu"), _T("hua"), _T("hua"), _T("hua"), _T("hua"), _T("hua"), _T("hua"), _T("hua"), _T("hua"), _T("hua"), _T("huai"), _T("huai"), _T("huai"), _T("huai"), _T("huai"), _T("huan"), _T("huan"), _T("huan"), _T("hai"), _T("huan"), _T("huan"), _T("huan"), _T("huan"), _T("huan"), _T("huan"), _T("huan"), _T("huan"), _T("huan"), _T("huan"), _T("huang"), _T("huang"), _T("huang"), _T("huang"), _T("huang"), _T("huang"), _T("huang"), _T("huang"), _T("huang"), _T("huang"), _T("huang"), _T("huang"), _T("huang"), _T("huang"), _T("hui"), _T("hui"), _T("hui"), _T("hui"), _T("hui"), _T("hui"), _T("hui"), _T("hui"), _T("hui"), _T("hui"), _T("hui"), _T("hui"), _T("hui"), _T("hui"), _T("hui"), _T("hui"), _T("hui"), _T("hui"), _T("hui"), _T("hui"), _T("hui"), _T("hun"), _T("hun"), _T("hun"), _T("hun"), _T("hun"), _T("hun"), _T("huo"), _T("huo"), _T("huo"), _T("huo"), _T("huo"), _T("huo"), _T("huo"), _T("huo"), _T("huo"), _T("huo"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), NULL};
const TCHAR* BC[] = {_T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("ji"), _T("jia"), _T("jia"), _T("ga"), _T("jia"), _T("jia"), _T("jia"), _T("jia"), _T("jia"), _T("gu"), _T("jia"), _T("jia"), _T("jia"), _T("jia"), _T("jia"), _T("jia"), _T("jia"), _T("jia"), _T("jian"), _T("jian"), _T("jian"), _T("jian"), _T("jian"), _T("jian"), _T("jian"), _T("jian"), _T("jian"), _T("jian"), _T("jian"), _T("jian"), _T("jian"), _T("jian"), _T("jian"), _T("jian"), _T("jian"), _T("jian"), _T("jian"), _T("jian"), _T("jian"), _T("jian"), _T("jian"), _T("jian"), _T("jian"), _T("jian"), _T("jian"), _T("jian"), _T("jian"), _T("jian"), _T("jian"), _T("jian"), NULL};
const TCHAR* BD[] = {_T("jian"), _T("jian"), _T("jian"), _T("jian"), _T("jian"), _T("jian"), _T("jian"), _T("jian"), _T("jiang"), _T("jiang"), _T("jiang"), _T("jiang"), _T("jiang"), _T("jiang"), _T("jiang"), _T("jiang"), _T("jiang"), _T("jiang"), _T("jiang"), _T("jiang"), _T("jiang"), _T("jiao"), _T("jiao"), _T("jiao"), _T("jiao"), _T("jiao"), _T("jiao"), _T("jiao"), _T("jiao"), _T("jiao"), _T("jiao"), _T("jiao"), _T("jiao"), _T("jiao"), _T("jiao"), _T("jiao"), _T("jiao"), _T("jiao"), _T("jiao"), _T("jiao"), _T("jiao"), _T("jiao"), _T("chao"), _T("jiao"), _T("jiao"), _T("jiao"), _T("jiao"), _T("jiao"), _T("jiao"), _T("jie"), _T("jie"), _T("jie"), _T("jie"), _T("jie"), _T("jie"), _T("jie"), _T("jie"), _T("jie"), _T("jie"), _T("jie"), _T("jie"), _T("jie"), _T("jie"), _T("jie"), _T("jie"), _T("jie"), _T("jie"), _T("jie"), _T("ji"), _T("gai"), _T("jie"), _T("jie"), _T("jie"), _T("jie"), _T("jie"), _T("jie"), _T("jin"), _T("jin"), _T("jin"), _T("jin"), _T("jin"), _T("jin"), _T("jin"), _T("jin"), _T("jin"), _T("jin"), _T("jin"), _T("jin"), _T("jin"), _T("jin"), _T("jin"), _T("jin"), _T("jin"), _T("jin"), NULL};
const TCHAR* BE[] = {_T("jin"), _T("jin"), _T("jing"), _T("jing"), _T("jing"), _T("jing"), _T("jing"), _T("jing"), _T("jing"), _T("jing"), _T("jing"), _T("jing"), _T("jing"), _T("jing"), _T("jing"), _T("jing"), _T("geng"), _T("jing"), _T("jing"), _T("jing"), _T("jing"), _T("jing"), _T("jing"), _T("jing"), _T("jing"), _T("jing"), _T("jing"), _T("jiong"), _T("jiong"), _T("jiu"), _T("jiu"), _T("jiu"), _T("jiu"), _T("jiu"), _T("jiu"), _T("jiu"), _T("jiu"), _T("jiu"), _T("jiu"), _T("jiu"), _T("jiu"), _T("jiu"), _T("jiu"), _T("jiu"), _T("jiu"), _T("jiu"), _T("ju"), _T("ju"), _T("ju"), _T("ju"), _T("ju"), _T("ju"), _T("ju"), _T("ju"), _T("ju"), _T("ju"), _T("ju"), _T("ju"), _T("ju"), _T("ju"), _T("ju"), _T("ju"), _T("ju"), _T("ju"), _T("ju"), _T("ju"), _T("ju"), _T("ju"), _T("ju"), _T("ju"), _T("ju"), _T("juan"), _T("juan"), _T("juan"), _T("juan"), _T("juan"), _T("juan"), _T("juan"), _T("jue"), _T("jue"), _T("jue"), _T("jue"), _T("jue"), _T("jue"), _T("jiao"), _T("jue"), _T("jue"), _T("jue"), _T("jun"), _T("jun"), _T("jun"), _T("jun"), _T("jun"), _T("jun"), NULL};
const TCHAR* BF[] = {_T("jun"), _T("jun"), _T("jun"), _T("jun"), _T("jun"), _T("ka"), _T("ga"), _T("ka"), _T("ge"), _T("kai"), _T("kai"), _T("kai"), _T("kai"), _T("kai"), _T("kan"), _T("kan"), _T("kan"), _T("kan"), _T("kan"), _T("kan"), _T("kang"), _T("kang"), _T("kang"), _T("gang"), _T("kang"), _T("kang"), _T("kang"), _T("kao"), _T("kao"), _T("kao"), _T("kao"), _T("ke"), _T("ke"), _T("ke"), _T("ke"), _T("ke"), _T("ke"), _T("ke"), _T("ke"), _T("hai"), _T("ke"), _T("ke"), _T("ke"), _T("ke"), _T("ke"), _T("ke"), _T("ken"), _T("ken"), _T("ken"), _T("ken"), _T("keng"), _T("hang"), _T("kong"), _T("kong"), _T("kong"), _T("kong"), _T("kou"), _T("kou"), _T("kou"), _T("kou"), _T("ku"), _T("ku"), _T("ku"), _T("ku"), _T("ku"), _T("ku"), _T("ku"), _T("kua"), _T("kua"), _T("kua"), _T("kua"), _T("kua"), _T("kuai"), _T("kuai"), _T("kuai"), _T("kuai"), _T("kuan"), _T("kuan"), _T("kuang"), _T("kuang"), _T("kuang"), _T("kuang"), _T("kuang"), _T("kuang"), _T("kuang"), _T("kuang"), _T("kui"), _T("kui"), _T("kui"), _T("kui"), _T("kui"), _T("kui"), _T("kui"), _T("kui"), NULL};
const TCHAR* C0[] = {_T("kui"), _T("kui"), _T("hui"), _T("kun"), _T("kun"), _T("kun"), _T("kun"), _T("kuo"), _T("kuo"), _T("kuo"), _T("kuo"), _T("la"), _T("la"), _T("la"), _T("la"), _T("la"), _T("la"), _T("la"), _T("lai"), _T("lai"), _T("lai"), _T("lan"), _T("lan"), _T("lan"), _T("lan"), _T("lan"), _T("lan"), _T("lan"), _T("lan"), _T("lan"), _T("lan"), _T("lan"), _T("lan"), _T("lan"), _T("lan"), _T("lan"), _T("lang"), _T("lang"), _T("lang"), _T("lang"), _T("lang"), _T("lang"), _T("lang"), _T("lao"), _T("lao"), _T("lao"), _T("lao"), _T("lao"), _T("lao"), _T("lao"), _T("lao"), _T("lao"), _T("le"), _T("le"), _T("lei"), _T("lei"), _T("lei"), _T("lei"), _T("lei"), _T("lei"), _T("lei"), _T("lei"), _T("lei"), _T("lei"), _T("lei"), _T("leng"), _T("leng"), _T("leng"), _T("li"), _T("li"), _T("li"), _T("li"), _T("li"), _T("li"), _T("li"), _T("li"), _T("li"), _T("li"), _T("li"), _T("li"), _T("li"), _T("li"), _T("li"), _T("li"), _T("li"), _T("li"), _T("li"), _T("li"), _T("li"), _T("li"), _T("li"), _T("li"), _T("li"), _T("li"), NULL};
const TCHAR* C1[] = {_T("li"), _T("li"), _T("li"), _T("li"), _T("li"), _T("li"), _T("li"), _T("li"), _T("lia"), _T("lian"), _T("lian"), _T("lian"), _T("lian"), _T("lian"), _T("lian"), _T("lian"), _T("lian"), _T("lian"), _T("lian"), _T("lian"), _T("lian"), _T("lian"), _T("lian"), _T("liang"), _T("liang"), _T("liang"), _T("liang"), _T("liang"), _T("liang"), _T("liang"), _T("liang"), _T("liang"), _T("liang"), _T("liang"), _T("liao"), _T("liao"), _T("liao"), _T("liao"), _T("liao"), _T("liao"), _T("liao"), _T("liao"), _T("le"), _T("liao"), _T("liao"), _T("liao"), _T("liao"), _T("lie"), _T("lie"), _T("lie"), _T("lie"), _T("lie"), _T("lin"), _T("lin"), _T("lin"), _T("lin"), _T("lin"), _T("lin"), _T("lin"), _T("lin"), _T("lin"), _T("lin"), _T("lin"), _T("lin"), _T("ling"), _T("ling"), _T("ling"), _T("ling"), _T("ling"), _T("ling"), _T("ling"), _T("ling"), _T("ling"), _T("ling"), _T("ling"), _T("ling"), _T("ling"), _T("ling"), _T("liu"), _T("liu"), _T("liu"), _T("liu"), _T("liu"), _T("liu"), _T("liu"), _T("liu"), _T("liu"), _T("liu"), _T("liu"), _T("long"), _T("long"), _T("long"), _T("long"), _T("long"), NULL};
const TCHAR* C2[] = {_T("long"), _T("long"), _T("long"), _T("long"), _T("lou"), _T("lou"), _T("lou"), _T("lou"), _T("lou"), _T("lou"), _T("lu"), _T("lu"), _T("lu"), _T("lu"), _T("lu"), _T("lu"), _T("lu"), _T("lu"), _T("lu"), _T("lu"), _T("liu"), _T("lou"), _T("lu"), _T("lu"), _T("lu"), _T("lu"), _T("lu"), _T("lu"), _T("liu"), _T("lu"), _T("lv"), _T("lv"), _T("lv"), _T("lv"), _T("lv"), _T("lv"), _T("lv"), _T("lv"), _T("lv"), _T("lv"), _T("lv"), _T("lv"), _T("lv"), _T("lu"), _T("luan"), _T("luan"), _T("luan"), _T("luan"), _T("luan"), _T("luan"), _T("lve"), _T("lve"), _T("lun"), _T("lun"), _T("lun"), _T("lun"), _T("lun"), _T("guan"), _T("lun"), _T("luo"), _T("luo"), _T("luo"), _T("luo"), _T("luo"), _T("luo"), _T("luo"), _T("luo"), _T("la"), _T("luo"), _T("luo"), _T("lao"), _T("ma"), _T("ma"), _T("ma"), _T("ma"), _T("ma"), _T("ma"), _T("ma"), _T("ma"), _T("ma"), _T("mai"), _T("mai"), _T("mai"), _T("mai"), _T("mai"), _T("mai"), _T("man"), _T("man"), _T("man"), _T("man"), _T("man"), _T("man"), _T("man"), _T("man"), NULL};
const TCHAR* C3[] = {_T("man"), _T("mang"), _T("mang"), _T("mang"), _T("mang"), _T("mang"), _T("mang"), _T("mao"), _T("mao"), _T("mao"), _T("mao"), _T("mao"), _T("mao"), _T("mao"), _T("mao"), _T("mao"), _T("mao"), _T("mao"), _T("mao"), _T("me"), _T("mei"), _T("mei"), _T("mei"), _T("mei"), _T("mei"), _T("mei"), _T("mei"), _T("mei"), _T("mei"), _T("mei"), _T("mei"), _T("mei"), _T("mei"), _T("mei"), _T("mei"), _T("mei"), _T("men"), _T("men"), _T("men"), _T("meng"), _T("meng"), _T("meng"), _T("meng"), _T("meng"), _T("meng"), _T("meng"), _T("meng"), _T("mi"), _T("mi"), _T("mi"), _T("mi"), _T("mi"), _T("mi"), _T("mi"), _T("mi"), _T("bi"), _T("mi"), _T("bi"), _T("mi"), _T("mi"), _T("mi"), _T("mian"), _T("mian"), _T("mian"), _T("mian"), _T("mian"), _T("mian"), _T("mian"), _T("mian"), _T("mian"), _T("miao"), _T("miao"), _T("miao"), _T("miao"), _T("miao"), _T("miao"), _T("miao"), _T("miao"), _T("mie"), _T("mie"), _T("min"), _T("min"), _T("min"), _T("min"), _T("min"), _T("min"), _T("ming"), _T("ming"), _T("ming"), _T("ming"), _T("ming"), _T("ming"), _T("miu"), _T("mo"), NULL};
const TCHAR* C4[] = {_T("mo"), _T("mo"), _T("mo"), _T("mo"), _T("mo"), _T("ma"), _T("mo"), _T("ma"), _T("mo"), _T("mo"), _T("mo"), _T("mo"), _T("mo"), _T("mo"), _T("mo"), _T("mo"), _T("mou"), _T("mou"), _T("mou"), _T("mu"), _T("mu"), _T("mu"), _T("mu"), _T("mu"), _T("mu"), _T("mu"), _T("mu"), _T("mu"), _T("mu"), _T("mu"), _T("mu"), _T("mu"), _T("mu"), _T("mu"), _T("na"), _T("na"), _T("na"), _T("na"), _T("na"), _T("na"), _T("na"), _T("nai"), _T("nai"), _T("nai"), _T("nai"), _T("nai"), _T("nan"), _T("nan"), _T("nan"), _T("nang"), _T("nao"), _T("nao"), _T("nao"), _T("nao"), _T("nao"), _T("ne"), _T("nei"), _T("nei"), _T("nen"), _T("neng"), _T("ni"), _T("ni"), _T("ni"), _T("ni"), _T("ni"), _T("ni"), _T("ni"), _T("ni"), _T("ni"), _T("ni"), _T("ni"), _T("nian"), _T("nian"), _T("nian"), _T("nian"), _T("nian"), _T("nian"), _T("nian"), _T("niang"), _T("niang"), _T("niao"), _T("niao"), _T("nie"), _T("nie"), _T("nie"), _T("nie"), _T("nie"), _T("nie"), _T("nie"), _T("nin"), _T("ning"), _T("ning"), _T("ning"), _T("ning"), NULL};
const TCHAR* C5[] = {_T("ning"), _T("ning"), _T("niu"), _T("niu"), _T("niu"), _T("niu"), _T("nong"), _T("nong"), _T("nong"), _T("long"), _T("nu"), _T("nu"), _T("nu"), _T("nv"), _T("nuan"), _T("nve"), _T("nve"), _T("nuo"), _T("nuo"), _T("nuo"), _T("nuo"), _T("e"), _T("ou"), _T("ou"), _T("ou"), _T("ou"), _T("ou"), _T("ou"), _T("ou"), _T("pa"), _T("pa"), _T("pa"), _T("pa"), _T("pa"), _T("pa"), _T("pai"), _T("pai"), _T("pai"), _T("pai"), _T("pai"), _T("pai"), _T("pan"), _T("pan"), _T("pan"), _T("pan"), _T("pan"), _T("pan"), _T("pan"), _T("pan"), _T("pang"), _T("pang"), _T("pang"), _T("pang"), _T("pan"), _T("pao"), _T("pao"), _T("bao"), _T("bao"), _T("pao"), _T("pao"), _T("pao"), _T("pei"), _T("pei"), _T("pei"), _T("pei"), _T("pei"), _T("pei"), _T("pei"), _T("pei"), _T("pei"), _T("pen"), _T("pen"), _T("peng"), _T("peng"), _T("peng"), _T("peng"), _T("peng"), _T("peng"), _T("peng"), _T("peng"), _T("peng"), _T("peng"), _T("peng"), _T("peng"), _T("peng"), _T("peng"), _T("pi"), _T("pi"), _T("pi"), _T("pi"), _T("pi"), _T("pi"), _T("pi"), _T("pi"), NULL};
const TCHAR* C6[] = {_T("pi"), _T("pi"), _T("pi"), _T("pi"), _T("pi"), _T("pi"), _T("pi"), _T("pi"), _T("pi"), _T("pian"), _T("pian"), _T("pian"), _T("pian"), _T("piao"), _T("piao"), _T("piao"), _T("piao"), _T("pie"), _T("pie"), _T("pin"), _T("pin"), _T("pin"), _T("pin"), _T("pin"), _T("ping"), _T("ping"), _T("ping"), _T("ping"), _T("ping"), _T("ping"), _T("ping"), _T("ping"), _T("bing"), _T("po"), _T("po"), _T("po"), _T("po"), _T("po"), _T("po"), _T("pai"), _T("po"), _T("pou"), _T("pu"), _T("pu"), _T("pu"), _T("pu"), _T("pu"), _T("pu"), _T("pu"), _T("bu"), _T("piao"), _T("pu"), _T("pu"), _T("pu"), _T("pu"), _T("pu"), _T("pu"), _T("qi"), _T("qi"), _T("qi"), _T("qi"), _T("qi"), _T("qi"), _T("qi"), _T("qi"), _T("qi"), _T("qi"), _T("qi"), _T("qi"), _T("ji"), _T("qi"), _T("qi"), _T("qi"), _T("qi"), _T("qi"), _T("qi"), _T("qi"), _T("qi"), _T("qi"), _T("qi"), _T("qi"), _T("qi"), _T("qi"), _T("qi"), _T("qi"), _T("qi"), _T("qi"), _T("qi"), _T("qi"), _T("qi"), _T("qi"), _T("qi"), _T("qi"), _T("qia"), NULL};
const TCHAR* C7[] = {_T("qia"), _T("qia"), _T("qian"), _T("qian"), _T("qian"), _T("qian"), _T("qian"), _T("qian"), _T("qian"), _T("qian"), _T("qian"), _T("qian"), _T("qian"), _T("qian"), _T("qian"), _T("qian"), _T("qian"), _T("qian"), _T("qian"), _T("qian"), _T("qian"), _T("qian"), _T("qian"), _T("qian"), _T("qiang"), _T("qiang"), _T("qiang"), _T("qiang"), _T("qiang"), _T("qiang"), _T("jiang"), _T("qiang"), _T("qiao"), _T("qiao"), _T("qiao"), _T("qiao"), _T("qiao"), _T("qiao"), _T("qiao"), _T("qiao"), _T("qiao"), _T("qiao"), _T("qiao"), _T("qiao"), _T("qiao"), _T("qiao"), _T("qiao"), _T("qie"), _T("jia"), _T("qie"), _T("qie"), _T("qie"), _T("qin"), _T("qin"), _T("qin"), _T("qin"), _T("qin"), _T("qin"), _T("qin"), _T("qin"), _T("qin"), _T("qin"), _T("qin"), _T("qing"), _T("qing"), _T("qing"), _T("qing"), _T("qing"), _T("qing"), _T("qing"), _T("qing"), _T("qing"), _T("qing"), _T("qing"), _T("qing"), _T("qing"), _T("qiong"), _T("qiong"), _T("qiu"), _T("qiu"), _T("qiu"), _T("qiu"), _T("qiu"), _T("qiu"), _T("qiu"), _T("qiu"), _T("qu"), _T("ou"), _T("qu"), _T("qu"), _T("qu"), _T("qu"), _T("qu"), _T("qu"), NULL};
const TCHAR* C8[] = {_T("qu"), _T("qu"), _T("qu"), _T("qu"), _T("qu"), _T("juan"), _T("quan"), _T("quan"), _T("quan"), _T("quan"), _T("quan"), _T("quan"), _T("quan"), _T("quan"), _T("quan"), _T("quan"), _T("que"), _T("gui"), _T("que"), _T("que"), _T("que"), _T("que"), _T("que"), _T("qiao"), _T("qun"), _T("qun"), _T("ran"), _T("ran"), _T("ran"), _T("ran"), _T("rang"), _T("rang"), _T("rang"), _T("rang"), _T("rang"), _T("rao"), _T("rao"), _T("rao"), _T("re"), _T("re"), _T("ren"), _T("ren"), _T("ren"), _T("ren"), _T("ren"), _T("ren"), _T("ren"), _T("ren"), _T("ren"), _T("ren"), _T("reng"), _T("reng"), _T("ri"), _T("rong"), _T("rong"), _T("rong"), _T("rong"), _T("rong"), _T("rong"), _T("rong"), _T("rong"), _T("rong"), _T("rong"), _T("rou"), _T("rou"), _T("rou"), _T("ru"), _T("ru"), _T("ru"), _T("ru"), _T("ru"), _T("ru"), _T("ru"), _T("ru"), _T("ru"), _T("ru"), _T("ruan"), _T("ruan"), _T("rui"), _T("rui"), _T("rui"), _T("run"), _T("run"), _T("ruo"), _T("ruo"), _T("sa"), _T("sa"), _T("sa"), _T("sai"), _T("sai"), _T("sai"), _T("sai"), _T("san"), _T("san"), NULL};
const TCHAR* C9[] = {_T("san"), _T("san"), _T("sang"), _T("sang"), _T("sang"), _T("sao"), _T("sao"), _T("sao"), _T("sao"), _T("se"), _T("se"), _T("se"), _T("sen"), _T("seng"), _T("sha"), _T("sha"), _T("sha"), _T("cha"), _T("sha"), _T("sha"), _T("sha"), _T("sha"), _T("sha"), _T("shai"), _T("shai"), _T("shan"), _T("shan"), _T("sha"), _T("shan"), _T("shan"), _T("shan"), _T("shan"), _T("shan"), _T("shan"), _T("shan"), _T("dan"), _T("shan"), _T("shan"), _T("shan"), _T("shan"), _T("shan"), _T("shang"), _T("shang"), _T("shang"), _T("shang"), _T("shang"), _T("shang"), _T("shang"), _T("shang"), _T("shao"), _T("shao"), _T("shao"), _T("shao"), _T("shao"), _T("shao"), _T("shao"), _T("shao"), _T("shao"), _T("shao"), _T("shao"), _T("she"), _T("she"), _T("she"), _T("she"), _T("she"), _T("she"), _T("she"), _T("she"), _T("she"), _T("she"), _T("she"), _T("she"), _T("shen"), _T("shen"), _T("shen"), _T("shen"), _T("shen"), _T("shen"), _T("shen"), _T("shen"), _T("shen"), _T("shen"), _T("shen"), _T("shen"), _T("shen"), _T("shen"), _T("shen"), _T("shen"), _T("sheng"), _T("sheng"), _T("sheng"), _T("sheng"), _T("sheng"), _T("sheng"), NULL};
const TCHAR* CA[] = {_T("sheng"), _T("cheng"), _T("sheng"), _T("sheng"), _T("sheng"), _T("shi"), _T("shi"), _T("shi"), _T("shi"), _T("shi"), _T("shi"), _T("shi"), _T("shi"), _T("shi"), _T("dan"), _T("shi"), _T("shi"), _T("shen"), _T("shi"), _T("shi"), _T("shi"), _T("shi"), _T("shi"), _T("shi"), _T("shi"), _T("shi"), _T("shi"), _T("shi"), _T("shi"), _T("shi"), _T("shi"), _T("shi"), _T("shi"), _T("shi"), _T("shi"), _T("shi"), _T("shi"), _T("shi"), _T("shi"), _T("shi"), _T("shi"), _T("shi"), _T("shi"), _T("shi"), _T("shi"), _T("shi"), _T("shi"), _T("shi"), _T("shi"), _T("shi"), _T("shi"), _T("shi"), _T("shou"), _T("shou"), _T("shou"), _T("shou"), _T("shou"), _T("shou"), _T("shou"), _T("shou"), _T("shou"), _T("shou"), _T("shu"), _T("shu"), _T("shu"), _T("shu"), _T("shu"), _T("shu"), _T("shu"), _T("shu"), _T("shu"), _T("shu"), _T("shu"), _T("shu"), _T("shu"), _T("shu"), _T("shu"), _T("shu"), _T("shu"), _T("shu"), _T("shu"), _T("shu"), _T("shu"), _T("shu"), _T("shu"), _T("shu"), _T("shu"), _T("shu"), _T("shu"), _T("shu"), _T("shu"), _T("shu"), _T("shu"), _T("shu"), NULL};
const TCHAR* CB[] = {_T("shu"), _T("shua"), _T("shua"), _T("shuai"), _T("shuai"), _T("shuai"), _T("shuai"), _T("shuan"), _T("shuan"), _T("shuang"), _T("shuang"), _T("shuang"), _T("shei"), _T("shui"), _T("shui"), _T("shui"), _T("shun"), _T("shun"), _T("shun"), _T("shun"), _T("shui"), _T("shuo"), _T("shuo"), _T("shuo"), _T("si"), _T("si"), _T("si"), _T("si"), _T("si"), _T("si"), _T("si"), _T("si"), _T("si"), _T("si"), _T("si"), _T("si"), _T("ci"), _T("shi"), _T("si"), _T("si"), _T("song"), _T("song"), _T("song"), _T("song"), _T("song"), _T("song"), _T("song"), _T("song"), _T("sou"), _T("sou"), _T("sou"), _T("sou"), _T("su"), _T("su"), _T("su"), _T("su"), _T("su"), _T("su"), _T("su"), _T("su"), _T("su"), _T("su"), _T("su"), _T("su"), _T("suan"), _T("suan"), _T("suan"), _T("sui"), _T("sui"), _T("sui"), _T("sui"), _T("sui"), _T("sui"), _T("sui"), _T("sui"), _T("sui"), _T("sui"), _T("sui"), _T("sun"), _T("sun"), _T("sun"), _T("suo"), _T("suo"), _T("suo"), _T("su"), _T("suo"), _T("suo"), _T("suo"), _T("suo"), _T("ta"), _T("ta"), _T("ta"), _T("ta"), _T("ta"), NULL};
const TCHAR* CC[] = {_T("ta"), _T("ta"), _T("ta"), _T("ta"), _T("tai"), _T("tai"), _T("tai"), _T("tai"), _T("tai"), _T("tai"), _T("tai"), _T("tai"), _T("tai"), _T("tan"), _T("tan"), _T("tan"), _T("tan"), _T("tan"), _T("tan"), _T("tan"), _T("tan"), _T("tan"), _T("tan"), _T("tan"), _T("tan"), _T("tan"), _T("tan"), _T("tan"), _T("tan"), _T("tan"), _T("tan"), _T("tang"), _T("tang"), _T("tang"), _T("tang"), _T("tang"), _T("tang"), _T("tang"), _T("tang"), _T("tang"), _T("tang"), _T("tang"), _T("tang"), _T("tang"), _T("tao"), _T("tao"), _T("tao"), _T("tao"), _T("tao"), _T("tao"), _T("tao"), _T("tao"), _T("tao"), _T("tao"), _T("tao"), _T("te"), _T("teng"), _T("teng"), _T("teng"), _T("teng"), _T("ti"), _T("ti"), _T("ti"), _T("ti"), _T("di"), _T("ti"), _T("ti"), _T("ti"), _T("ti"), _T("ti"), _T("ti"), _T("ti"), _T("ti"), _T("ti"), _T("ti"), _T("tian"), _T("tian"), _T("tian"), _T("tian"), _T("tian"), _T("tian"), _T("tian"), _T("tian"), _T("tiao"), _T("tiao"), _T("tiao"), _T("tiao"), _T("tiao"), _T("tie"), _T("tie"), _T("tie"), _T("ting"), _T("ting"), _T("ting"), NULL};
const TCHAR* CD[] = {_T("ting"), _T("ting"), _T("ting"), _T("ting"), _T("ting"), _T("ting"), _T("ting"), _T("tong"), _T("tong"), _T("tong"), _T("tong"), _T("tong"), _T("tong"), _T("tong"), _T("tong"), _T("tong"), _T("tong"), _T("tong"), _T("tong"), _T("tong"), _T("tou"), _T("tou"), _T("tou"), _T("tou"), _T("tu"), _T("tu"), _T("tu"), _T("tu"), _T("tu"), _T("tu"), _T("tu"), _T("tu"), _T("tu"), _T("tu"), _T("tu"), _T("tuan"), _T("tuan"), _T("tui"), _T("tui"), _T("tui"), _T("tui"), _T("tui"), _T("tui"), _T("tun"), _T("tun"), _T("tun"), _T("tuo"), _T("tuo"), _T("tuo"), _T("tuo"), _T("tuo"), _T("duo"), _T("tuo"), _T("tuo"), _T("tuo"), _T("ta"), _T("tuo"), _T("wa"), _T("wa"), _T("wa"), _T("wa"), _T("wa"), _T("wa"), _T("wa"), _T("wai"), _T("wai"), _T("wan"), _T("wan"), _T("wan"), _T("wan"), _T("wan"), _T("wan"), _T("wan"), _T("wan"), _T("wan"), _T("wan"), _T("wan"), _T("wan"), _T("wan"), _T("wan"), _T("wan"), _T("mo"), _T("wan"), _T("wang"), _T("wang"), _T("wang"), _T("wang"), _T("wang"), _T("wang"), _T("wang"), _T("wang"), _T("wang"), _T("wang"), _T("wei"), NULL};
const TCHAR* CE[] = {_T("wei"), _T("wei"), _T("wei"), _T("wei"), _T("wei"), _T("wei"), _T("wei"), _T("wei"), _T("wei"), _T("wei"), _T("wei"), _T("wei"), _T("wei"), _T("wei"), _T("wei"), _T("wei"), _T("wei"), _T("wei"), _T("wei"), _T("wei"), _T("wei"), _T("wei"), _T("wei"), _T("wei"), _T("wei"), _T("wei"), _T("wei"), _T("wei"), _T("wei"), _T("wei"), _T("wei"), _T("wei"), _T("wen"), _T("wen"), _T("wen"), _T("wen"), _T("wen"), _T("wen"), _T("wen"), _T("wen"), _T("wen"), _T("wen"), _T("weng"), _T("weng"), _T("weng"), _T("wo"), _T("wo"), _T("guo"), _T("wo"), _T("wo"), _T("wo"), _T("wo"), _T("wo"), _T("wo"), _T("wu"), _T("wu"), _T("wu"), _T("wu"), _T("wu"), _T("wu"), _T("wu"), _T("wu"), _T("wu"), _T("wu"), _T("wu"), _T("wu"), _T("wu"), _T("wu"), _T("wu"), _T("wu"), _T("wu"), _T("wu"), _T("wu"), _T("wu"), _T("wu"), _T("wu"), _T("wu"), _T("wu"), _T("wu"), _T("wu"), _T("wu"), _T("wu"), _T("wu"), _T("xi"), _T("xi"), _T("xi"), _T("xi"), _T("xi"), _T("xi"), _T("xi"), _T("xi"), _T("xi"), _T("xi"), _T("xi"), NULL};
const TCHAR* CF[] = {_T("xi"), _T("xi"), _T("xi"), _T("xi"), _T("xi"), _T("xi"), _T("xi"), _T("xi"), _T("xi"), _T("xi"), _T("xi"), _T("xi"), _T("xi"), _T("xi"), _T("xi"), _T("xi"), _T("xi"), _T("xi"), _T("xi"), _T("xi"), _T("ji"), _T("xi"), _T("xi"), _T("xi"), _T("xia"), _T("xia"), _T("xia"), _T("xia"), _T("xia"), _T("xia"), _T("xia"), _T("xia"), _T("xia"), _T("xia"), _T("sha"), _T("xia"), _T("he"), _T("xian"), _T("xian"), _T("xian"), _T("xian"), _T("xian"), _T("qian"), _T("xian"), _T("xian"), _T("xian"), _T("xian"), _T("xian"), _T("xian"), _T("xian"), _T("xian"), _T("xian"), _T("xian"), _T("xian"), _T("xian"), _T("xian"), _T("xian"), _T("xian"), _T("xian"), _T("xian"), _T("xian"), _T("xian"), _T("xian"), _T("xiang"), _T("xiang"), _T("xiang"), _T("xiang"), _T("xiang"), _T("xiang"), _T("xiang"), _T("xiang"), _T("xiang"), _T("xiang"), _T("xiang"), _T("xiang"), _T("xiang"), _T("xiang"), _T("xiang"), _T("hang"), _T("xiang"), _T("xiang"), _T("xiang"), _T("xiang"), _T("xiao"), _T("xiao"), _T("xiao"), _T("xiao"), _T("xiao"), _T("xiao"), _T("xiao"), _T("xiao"), _T("xiao"), _T("xiao"), _T("xiao"), NULL};
const TCHAR* D0[] = {_T("xiao"), _T("xiao"), _T("jiao"), _T("xiao"), _T("xiao"), _T("xiao"), _T("xiao"), _T("xie"), _T("xie"), _T("xie"), _T("xie"), _T("xie"), _T("xie"), _T("xie"), _T("xie"), _T("xie"), _T("xie"), _T("xie"), _T("xie"), _T("xie"), _T("xie"), _T("xie"), _T("xie"), _T("xie"), _T("xie"), _T("xie"), _T("xie"), _T("xie"), _T("xin"), _T("xin"), _T("xin"), _T("xin"), _T("xin"), _T("xin"), _T("xin"), _T("xin"), _T("xin"), _T("xin"), _T("xing"), _T("xing"), _T("xing"), _T("xing"), _T("xing"), _T("xing"), _T("xing"), _T("xing"), _T("xing"), _T("hang"), _T("xing"), _T("xing"), _T("xing"), _T("xing"), _T("xing"), _T("xiong"), _T("xiong"), _T("xiong"), _T("xiong"), _T("xiong"), _T("xiong"), _T("xiong"), _T("xiu"), _T("xiu"), _T("xiu"), _T("xiu"), _T("xiu"), _T("xiu"), _T("xiu"), _T("xiu"), _T("xiu"), _T("xu"), _T("qu"), _T("xu"), _T("xu"), _T("xu"), _T("xu"), _T("xu"), _T("xu"), _T("xu"), _T("xu"), _T("xu"), _T("xu"), _T("xu"), _T("chu"), _T("xu"), _T("xu"), _T("xu"), _T("xu"), _T("xu"), _T("xuan"), _T("xuan"), _T("xuan"), _T("xuan"), _T("xuan"), _T("xuan"), NULL};
const TCHAR* D1[] = {_T("xuan"), _T("xuan"), _T("xuan"), _T("xuan"), _T("xue"), _T("xue"), _T("xue"), _T("xue"), _T("xue"), _T("xie"), _T("xun"), _T("xun"), _T("xun"), _T("xun"), _T("xun"), _T("xun"), _T("xun"), _T("xun"), _T("xun"), _T("xun"), _T("xun"), _T("xun"), _T("xun"), _T("xun"), _T("ya"), _T("ya"), _T("ya"), _T("ya"), _T("ya"), _T("ya"), _T("ya"), _T("ya"), _T("ya"), _T("ya"), _T("ya"), _T("ya"), _T("ya"), _T("ya"), _T("ya"), _T("ya"), _T("yan"), _T("yan"), _T("yan"), _T("yan"), _T("yan"), _T("yan"), _T("yan"), _T("yan"), _T("yan"), _T("yan"), _T("yan"), _T("yan"), _T("yan"), _T("yan"), _T("yan"), _T("yan"), _T("yan"), _T("yan"), _T("yan"), _T("yan"), _T("yan"), _T("yan"), _T("yan"), _T("yan"), _T("yan"), _T("yan"), _T("yan"), _T("yan"), _T("yan"), _T("yan"), _T("yan"), _T("yan"), _T("yan"), _T("yang"), _T("yang"), _T("yang"), _T("yang"), _T("yang"), _T("yang"), _T("yang"), _T("yang"), _T("yang"), _T("yang"), _T("yang"), _T("yang"), _T("yang"), _T("yang"), _T("yang"), _T("yang"), _T("yang"), _T("yao"), _T("yao"), _T("yao"), _T("yao"), NULL};
const TCHAR* D2[] = {_T("yao"), _T("yao"), _T("yao"), _T("yao"), _T("yao"), _T("yao"), _T("yao"), _T("yao"), _T("yao"), _T("yao"), _T("yao"), _T("ye"), _T("ye"), _T("ye"), _T("ye"), _T("ye"), _T("ye"), _T("ye"), _T("ye"), _T("ye"), _T("ye"), _T("xie"), _T("ye"), _T("ye"), _T("ye"), _T("ye"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yi"), _T("yin"), _T("yin"), _T("yin"), _T("yan"), _T("yin"), _T("yin"), _T("yin"), _T("yin"), _T("yin"), _T("yin"), _T("yin"), _T("yin"), _T("yin"), _T("yin"), _T("yin"), NULL};
const TCHAR* D3[] = {_T("yin"), _T("ying"), _T("ying"), _T("ying"), _T("ying"), _T("ying"), _T("ying"), _T("ying"), _T("ying"), _T("ying"), _T("ying"), _T("ying"), _T("ying"), _T("ying"), _T("ying"), _T("ying"), _T("ying"), _T("ying"), _T("ying"), _T("yo"), _T("yong"), _T("yong"), _T("yong"), _T("yong"), _T("yong"), _T("yong"), _T("yong"), _T("yong"), _T("yong"), _T("yong"), _T("yong"), _T("yong"), _T("yong"), _T("yong"), _T("yong"), _T("you"), _T("you"), _T("you"), _T("you"), _T("you"), _T("you"), _T("you"), _T("you"), _T("you"), _T("you"), _T("you"), _T("you"), _T("you"), _T("you"), _T("you"), _T("you"), _T("you"), _T("you"), _T("you"), _T("you"), _T("yu"), _T("yu"), _T("yu"), _T("yu"), _T("yu"), _T("yu"), _T("yu"), _T("yu"), _T("yu"), _T("yu"), _T("yu"), _T("yu"), _T("yu"), _T("yu"), _T("yu"), _T("yu"), _T("yu"), _T("yu"), _T("yu"), _T("yu"), _T("yu"), _T("yu"), _T("yu"), _T("yu"), _T("yu"), _T("yu"), _T("yu"), _T("yu"), _T("yu"), _T("xu"), _T("yu"), _T("yu"), _T("yu"), _T("yu"), _T("yu"), _T("yu"), _T("yu"), _T("yo"), _T("yu"), NULL};
const TCHAR* D4[] = {_T("yu"), _T("yu"), _T("yu"), _T("yu"), _T("yu"), _T("yu"), _T("yuan"), _T("yuan"), _T("yuan"), _T("yuan"), _T("yuan"), _T("yuan"), _T("yuan"), _T("yuan"), _T("yuan"), _T("yuan"), _T("yuan"), _T("yuan"), _T("yuan"), _T("yuan"), _T("yuan"), _T("yuan"), _T("yuan"), _T("yuan"), _T("yuan"), _T("yuan"), _T("yue"), _T("yue"), _T("yue"), _T("yue"), _T("yao"), _T("yue"), _T("yue"), _T("yue"), _T("yue"), _T("yue"), _T("yun"), _T("yun"), _T("yun"), _T("yun"), _T("yun"), _T("yun"), _T("yun"), _T("yun"), _T("yun"), _T("yun"), _T("yun"), _T("yun"), _T("za"), _T("za"), _T("za"), _T("zai"), _T("zai"), _T("zai"), _T("zai"), _T("zai"), _T("zai"), _T("zai"), _T("zan"), _T("cuan"), _T("zan"), _T("zan"), _T("zang"), _T("zang"), _T("zang"), _T("zao"), _T("zao"), _T("zao"), _T("zao"), _T("zao"), _T("zao"), _T("zao"), _T("zao"), _T("zao"), _T("zao"), _T("zao"), _T("zao"), _T("zao"), _T("zao"), _T("ze"), _T("ze"), _T("ze"), _T("ze"), _T("zei"), _T("zen"), _T("zeng"), _T("zeng"), _T("ceng"), _T("zeng"), _T("za"), _T("cha"), _T("zha"), _T("zha"), _T("ya"), NULL};
const TCHAR* D5[] = {_T("zha"), _T("zha"), _T("zha"), _T("shan"), _T("zha"), _T("za"), _T("zha"), _T("zha"), _T("zha"), _T("zhai"), _T("zhai"), _T("zhai"), _T("zhai"), _T("zhai"), _T("zhai"), _T("zhan"), _T("zhan"), _T("zhan"), _T("zhan"), _T("zhan"), _T("zhan"), _T("zhan"), _T("zhan"), _T("zhan"), _T("zhan"), _T("zhan"), _T("zhan"), _T("zhan"), _T("zhan"), _T("zhan"), _T("zhan"), _T("zhan"), _T("zhang"), _T("zhang"), _T("zhang"), _T("zhang"), _T("zhang"), _T("zhang"), _T("zhang"), _T("zhang"), _T("zhang"), _T("zhang"), _T("zhang"), _T("zhang"), _T("zhang"), _T("zhang"), _T("zhang"), _T("zhao"), _T("zhao"), _T("zhao"), _T("zhao"), _T("zhao"), _T("zhao"), _T("zhao"), _T("zhao"), _T("zhao"), _T("zhao"), _T("zhe"), _T("she"), _T("zhe"), _T("zhe"), _T("zhe"), _T("zhe"), _T("zhe"), _T("zhe"), _T("zhe"), _T("zhe"), _T("zhen"), _T("zhen"), _T("zhen"), _T("zhen"), _T("zhen"), _T("zhen"), _T("zhen"), _T("zhen"), _T("zhen"), _T("zhen"), _T("zhen"), _T("zhen"), _T("zhen"), _T("zhen"), _T("zhen"), _T("zhen"), _T("zheng"), _T("zheng"), _T("zheng"), _T("zheng"), _T("zheng"), _T("zheng"), _T("zheng"), _T("zheng"), _T("zheng"), _T("zheng"), _T("zheng"), NULL};
const TCHAR* D6[] = {_T("zhen"), _T("zheng"), _T("zheng"), _T("zheng"), _T("zhi"), _T("zhi"), _T("zhi"), _T("zhi"), _T("zhi"), _T("zhi"), _T("zhi"), _T("zhi"), _T("zhi"), _T("zhi"), _T("zhi"), _T("zhi"), _T("zhi"), _T("zhi"), _T("shi"), _T("zhi"), _T("zhi"), _T("zhi"), _T("zhi"), _T("zhi"), _T("zhi"), _T("zhi"), _T("zhi"), _T("zhi"), _T("zhi"), _T("zhi"), _T("zhi"), _T("zhi"), _T("zhi"), _T("zhi"), _T("zhi"), _T("zhi"), _T("shi"), _T("zhi"), _T("zhi"), _T("zhi"), _T("zhi"), _T("zhi"), _T("zhi"), _T("zhi"), _T("zhi"), _T("zhi"), _T("zhi"), _T("zhong"), _T("ye"), _T("zhong"), _T("zhong"), _T("zhong"), _T("zhong"), _T("chong"), _T("zhong"), _T("chong"), _T("zhong"), _T("zhong"), _T("zhou"), _T("zhou"), _T("zhou"), _T("zhou"), _T("zhou"), _T("zhou"), _T("zhou"), _T("zhou"), _T("zhou"), _T("zhou"), _T("zhou"), _T("zhou"), _T("zhou"), _T("zhou"), _T("zhu"), _T("zhu"), _T("zhu"), _T("zhu"), _T("zhu"), _T("zhu"), _T("zhu"), _T("zhu"), _T("zhu"), _T("zhu"), _T("zhu"), _T("zhu"), _T("zhu"), _T("zhu"), _T("zhu"), _T("zhu"), _T("zhu"), _T("zhu"), _T("zhu"), _T("zhu"), _T("zhu"), _T("zhu"), NULL};
const TCHAR* D7[] = {_T("zhu"), _T("zhu"), _T("zhu"), _T("zhu"), _T("zhua"), _T("zhao"), _T("zhuai"), _T("zhuan"), _T("zhuan"), _T("zhuai"), _T("zhuan"), _T("zhuan"), _T("zhuan"), _T("zhuang"), _T("zhuang"), _T("zhuang"), _T("zhuang"), _T("zhuang"), _T("zhuang"), _T("zhuang"), _T("zhui"), _T("zhui"), _T("zhui"), _T("zhui"), _T("zhui"), _T("zhui"), _T("zhun"), _T("zhun"), _T("zhuo"), _T("zhuo"), _T("zhuo"), _T("zhuo"), _T("zhuo"), _T("zhuo"), _T("zhuo"), _T("zhuo"), _T("zhao"), _T("zhuo"), _T("zhuo"), _T("ci"), _T("zi"), _T("zi"), _T("zi"), _T("zi"), _T("zi"), _T("zi"), _T("zi"), _T("zi"), _T("zi"), _T("zi"), _T("zi"), _T("zi"), _T("zi"), _T("zi"), _T("zong"), _T("zong"), _T("zong"), _T("zong"), _T("zong"), _T("zong"), _T("zong"), _T("zou"), _T("zou"), _T("zou"), _T("zou"), _T("zu"), _T("zu"), _T("zu"), _T("zu"), _T("zu"), _T("zu"), _T("zu"), _T("zu"), _T("zuan"), _T("zuan"), _T("zui"), _T("zui"), _T("zui"), _T("zui"), _T("zun"), _T("zun"), _T("zuo"), _T("zuo"), _T("zuo"), _T("zha"), _T("zuo"), _T("zuo"), _T("zuo"), _T("zuo"), NULL};
const TCHAR* D8[] = {_T("chu"), _T("ji"), _T("wu"), _T("gai"), _T("nian"), _T("sa"), _T("pi"), _T("gen"), _T("cheng"), _T("ge"), _T("nao"), _T("e"), _T("shu"), _T("yu"), _T("pie"), _T("bi"), _T("tuo"), _T("yao"), _T("yao"), _T("zhi"), _T("di"), _T("xin"), _T("yin"), _T("kui"), _T("yu"), _T("gao"), _T("tao"), _T("zhu"), _T("ji"), _T("nai"), _T("mie"), _T("ji"), _T("qi"), _T("mi"), _T("bei"), _T("se"), _T("gu"), _T("ze"), _T("she"), _T("cuo"), _T("yan"), _T("jue"), _T("si"), _T("ye"), _T("yan"), _T("fang"), _T("po"), _T("gui"), _T("kui"), _T("bian"), _T("ze"), _T("gua"), _T("you"), _T("dao"), _T("yi"), _T("wen"), _T("jing"), _T("ku"), _T("gui"), _T("kai"), _T("la"), _T("ji"), _T("shan"), _T("wan"), _T("kuai"), _T("piao"), _T("jue"), _T("qiao"), _T("huo"), _T("yi"), _T("jiong"), _T("wang"), _T("ren"), _T("ding"), _T("zhang"), _T("le"), _T("sa"), _T("ge"), _T("mu"), _T("ren"), _T("yu"), _T("pi"), _T("ya"), _T("wa"), _T("wu"), _T("chang"), _T("cang"), _T("kang"), _T("zhu"), _T("ning"), _T("ka"), _T("you"), _T("yi"), _T("gou"), NULL};
const TCHAR* D9[] = {_T("tong"), _T("tuo"), _T("ni"), _T("ga"), _T("ji"), _T("nai"), _T("you"), _T("kua"), _T("kan"), _T("zhu"), _T("yi"), _T("tiao"), _T("chai"), _T("jiao"), _T("nong"), _T("mou"), _T("chou"), _T("yan"), _T("li"), _T("qiu"), _T("li"), _T("yu"), _T("ping"), _T("yong"), _T("qi"), _T("feng"), _T("qian"), _T("ruo"), _T("pai"), _T("zhuo"), _T("shu"), _T("luo"), _T("wo"), _T("bi"), _T("ti"), _T("guan"), _T("kong"), _T("ju"), _T("fen"), _T("yan"), _T("xie"), _T("ji"), _T("wei"), _T("zong"), _T("lou"), _T("tang"), _T("bin"), _T("nuo"), _T("chi"), _T("xi"), _T("jing"), _T("jian"), _T("jiao"), _T("jiu"), _T("tong"), _T("xuan"), _T("dan"), _T("tong"), _T("tun"), _T("she"), _T("qian"), _T("zu"), _T("yue"), _T("cuan"), _T("di"), _T("xi"), _T("xun"), _T("hong"), _T("guo"), _T("chan"), _T("kui"), _T("bao"), _T("pu"), _T("hong"), _T("fu"), _T("fu"), _T("su"), _T("si"), _T("tou"), _T("yan"), _T("bo"), _T("gun"), _T("mao"), _T("xie"), _T("luan"), _T("pou"), _T("bing"), _T("ying"), _T("luo"), _T("lei"), _T("bing"), _T("hu"), _T("lie"), _T("xian"), NULL};
const TCHAR* DA[] = {_T("song"), _T("mi"), _T("zhong"), _T("ming"), _T("yan"), _T("jie"), _T("hong"), _T("shan"), _T("ou"), _T("ju"), _T("ne"), _T("gu"), _T("he"), _T("di"), _T("zhao"), _T("qu"), _T("yi"), _T("kuang"), _T("lei"), _T("gua"), _T("jie"), _T("hui"), _T("shen"), _T("gou"), _T("quan"), _T("zheng"), _T("hun"), _T("xu"), _T("qiao"), _T("gao"), _T("kuang"), _T("ei"), _T("zou"), _T("zhuo"), _T("wei"), _T("yu"), _T("shen"), _T("chan"), _T("sui"), _T("chen"), _T("jian"), _T("xue"), _T("ye"), _T("e"), _T("yu"), _T("xuan"), _T("an"), _T("di"), _T("zi"), _T("pian"), _T("mo"), _T("dang"), _T("su"), _T("shi"), _T("mi"), _T("zhe"), _T("jian"), _T("jian"), _T("qiao"), _T("jue"), _T("yan"), _T("zhan"), _T("chen"), _T("jie"), _T("jin"), _T("fu"), _T("wu"), _T("qian"), _T("jing"), _T("ban"), _T("dian"), _T("zuo"), _T("bei"), _T("jing"), _T("gai"), _T("zhi"), _T("nie"), _T("zou"), _T("chui"), _T("pi"), _T("wei"), _T("huang"), _T("kui"), _T("xi"), _T("han"), _T("qiong"), _T("kuang"), _T("mang"), _T("wu"), _T("fang"), _T("bing"), _T("pi"), _T("bei"), _T("ye"), NULL};
const TCHAR* DB[] = {_T("di"), _T("tai"), _T("jia"), _T("zhi"), _T("zhu"), _T("kuai"), _T("qie"), _T("huan"), _T("yun"), _T("li"), _T("ying"), _T("gao"), _T("xi"), _T("fu"), _T("pi"), _T("tan"), _T("yan"), _T("juan"), _T("yan"), _T("yin"), _T("zhang"), _T("po"), _T("shan"), _T("zou"), _T("ling"), _T("feng"), _T("chu"), _T("huan"), _T("mai"), _T("qu"), _T("shao"), _T("he"), _T("ge"), _T("meng"), _T("xu"), _T("xie"), _T("sou"), _T("xie"), _T("jue"), _T("yin"), _T("kan"), _T("dang"), _T("chang"), _T("si"), _T("bian"), _T("ben"), _T("qiu"), _T("ben"), _T("e"), _T("fa"), _T("shu"), _T("ji"), _T("yong"), _T("he"), _T("wei"), _T("wu"), _T("ge"), _T("zhen"), _T("kuang"), _T("pi"), _T("yi"), _T("li"), _T("qi"), _T("ban"), _T("gan"), _T("long"), _T("dian"), _T("lu"), _T("che"), _T("chi"), _T("tuo"), _T("ni"), _T("mu"), _T("ao"), _T("ya"), _T("die"), _T("tong"), _T("kai"), _T("shan"), _T("shang"), _T("nao"), _T("gai"), _T("yin"), _T("cheng"), _T("shi"), _T("guo"), _T("xun"), _T("lie"), _T("huan"), _T("zhi"), _T("an"), _T("yi"), _T("bei"), _T("nian"), NULL};
const TCHAR* DC[] = {_T("beng"), _T("tu"), _T("sao"), _T("dai"), _T("jue"), _T("die"), _T("yin"), _T("leng"), _T("hou"), _T("ge"), _T("yuan"), _T("man"), _T("yong"), _T("liang"), _T("chi"), _T("xin"), _T("pi"), _T("yi"), _T("cao"), _T("jiao"), _T("nai"), _T("du"), _T("qian"), _T("ji"), _T("wan"), _T("xiong"), _T("qi"), _T("xiang"), _T("fu"), _T("yan"), _T("yun"), _T("fei"), _T("ji"), _T("li"), _T("e"), _T("ju"), _T("bi"), _T("zhi"), _T("rui"), _T("xian"), _T("chang"), _T("cong"), _T("qin"), _T("wu"), _T("qian"), _T("qi"), _T("shan"), _T("bian"), _T("zhu"), _T("kou"), _T("yi"), _T("mo"), _T("gan"), _T("pie"), _T("long"), _T("ba"), _T("mu"), _T("ju"), _T("ran"), _T("qing"), _T("chi"), _T("fu"), _T("ling"), _T("niao"), _T("yin"), _T("mao"), _T("ying"), _T("qiong"), _T("min"), _T("shao"), _T("qian"), _T("ti"), _T("rao"), _T("bi"), _T("ci"), _T("ju"), _T("tong"), _T("hui"), _T("zhu"), _T("ting"), _T("qiao"), _T("fu"), _T("ren"), _T("xing"), _T("quan"), _T("hui"), _T("xun"), _T("ming"), _T("ji"), _T("jiao"), _T("chong"), _T("jiang"), _T("luo"), _T("xing"), NULL};
const TCHAR* DD[] = {_T("qian"), _T("gen"), _T("jin"), _T("mai"), _T("sun"), _T("hong"), _T("zhou"), _T("kan"), _T("bi"), _T("shi"), _T("wo"), _T("you"), _T("e"), _T("mei"), _T("you"), _T("li"), _T("tu"), _T("xian"), _T("fu"), _T("sui"), _T("you"), _T("di"), _T("shen"), _T("guan"), _T("lang"), _T("ying"), _T("chun"), _T("jing"), _T("ji"), _T("xi"), _T("song"), _T("jin"), _T("nai"), _T("qi"), _T("ba"), _T("shu"), _T("chang"), _T("tie"), _T("yu"), _T("huan"), _T("bei"), _T("fu"), _T("tu"), _T("dan"), _T("cui"), _T("yan"), _T("zu"), _T("dang"), _T("jian"), _T("wan"), _T("ying"), _T("gu"), _T("han"), _T("qia"), _T("feng"), _T("ren"), _T("xiang"), _T("wei"), _T("chan"), _T("kai"), _T("qi"), _T("kui"), _T("xi"), _T("e"), _T("bao"), _T("pa"), _T("ting"), _T("lou"), _T("pai"), _T("xuan"), _T("jia"), _T("zhen"), _T("shi"), _T("ru"), _T("mo"), _T("en"), _T("bei"), _T("weng"), _T("hao"), _T("ji"), _T("li"), _T("bang"), _T("jian"), _T("shuo"), _T("lang"), _T("ying"), _T("yu"), _T("su"), _T("meng"), _T("dou"), _T("xi"), _T("lian"), _T("cu"), _T("lin"), NULL};
const TCHAR* DE[] = {_T("qu"), _T("kou"), _T("xu"), _T("liao"), _T("hui"), _T("xun"), _T("jue"), _T("rui"), _T("zui"), _T("ji"), _T("meng"), _T("bo"), _T("qi"), _T("hong"), _T("xie"), _T("hong"), _T("wei"), _T("yi"), _T("weng"), _T("sou"), _T("bi"), _T("hao"), _T("tai"), _T("ru"), _T("xun"), _T("xian"), _T("gao"), _T("li"), _T("huo"), _T("qu"), _T("heng"), _T("fan"), _T("nie"), _T("mi"), _T("gong"), _T("yi"), _T("kuang"), _T("lian"), _T("da"), _T("yi"), _T("xi"), _T("zhuang"), _T("pao"), _T("wang"), _T("liao"), _T("ga"), _T("gan"), _T("shou"), _T("men"), _T("tuan"), _T("chen"), _T("fu"), _T("pan"), _T("ao"), _T("jie"), _T("jiao"), _T("za"), _T("yi"), _T("lv"), _T("jun"), _T("tian"), _T("ye"), _T("ai"), _T("na"), _T("ji"), _T("guai"), _T("bai"), _T("ju"), _T("pou"), _T("lie"), _T("qian"), _T("guan"), _T("die"), _T("zha"), _T("ya"), _T("qin"), _T("yu"), _T("an"), _T("xuan"), _T("bing"), _T("kui"), _T("yuan"), _T("shu"), _T("en"), _T("chuai"), _T("jian"), _T("shuo"), _T("zhan"), _T("nuo"), _T("sang"), _T("luo"), _T("ying"), _T("zhi"), _T("han"), NULL};
const TCHAR* DF[] = {_T("zhe"), _T("xie"), _T("lu"), _T("zun"), _T("cuan"), _T("gan"), _T("huan"), _T("pi"), _T("xing"), _T("zhuo"), _T("huo"), _T("zuan"), _T("nang"), _T("yi"), _T("te"), _T("dai"), _T("shi"), _T("bu"), _T("chi"), _T("ji"), _T("kou"), _T("dao"), _T("le"), _T("zha"), _T("a"), _T("yao"), _T("fu"), _T("m"), _T("yi"), _T("dai"), _T("li"), _T("e"), _T("bi"), _T("bei"), _T("guo"), _T("qin"), _T("yin"), _T("za"), _T("ka"), _T("xia"), _T("gua"), _T("ling"), _T("dong"), _T("ning"), _T("duo"), _T("nao"), _T("you"), _T("si"), _T("kuang"), _T("ji"), _T("shen"), _T("hui"), _T("da"), _T("lie"), _T("yi"), _T("xiao"), _T("bi"), _T("ci"), _T("guang"), _T("hui"), _T("xiu"), _T("yi"), _T("pai"), _T("kuai"), _T("duo"), _T("ji"), _T("mie"), _T("mi"), _T("zha"), _T("nong"), _T("gen"), _T("mou"), _T("ma"), _T("chi"), _T("lao"), _T("geng"), _T("wu"), _T("zha"), _T("suo"), _T("zao"), _T("xi"), _T("zuo"), _T("ji"), _T("feng"), _T("ze"), _T("nuo"), _T("miao"), _T("lin"), _T("zhuan"), _T("zhao"), _T("tao"), _T("hu"), _T("cui"), _T("sha"), NULL};
const TCHAR* E0[] = {_T("yo"), _T("dan"), _T("bo"), _T("ding"), _T("lang"), _T("li"), _T("shua"), _T("chuo"), _T("die"), _T("da"), _T("nan"), _T("li"), _T("kui"), _T("jie"), _T("yong"), _T("kui"), _T("jiu"), _T("sou"), _T("yin"), _T("chi"), _T("jie"), _T("lou"), _T("ku"), _T("o"), _T("hui"), _T("qin"), _T("ao"), _T("su"), _T("du"), _T("ke"), _T("nie"), _T("he"), _T("chen"), _T("suo"), _T("ge"), _T("a"), _T("ng"), _T("hao"), _T("dia"), _T("ai"), _T("ai"), _T("suo"), _T("hai"), _T("tong"), _T("chi"), _T("pei"), _T("lei"), _T("cao"), _T("piao"), _T("qi"), _T("ying"), _T("beng"), _T("sou"), _T("di"), _T("mi"), _T("peng"), _T("jue"), _T("liao"), _T("pu"), _T("chuai"), _T("jiao"), _T("o"), _T("qin"), _T("lu"), _T("ceng"), _T("deng"), _T("hao"), _T("jin"), _T("xue"), _T("yi"), _T("sai"), _T("pi"), _T("ru"), _T("ca"), _T("huo"), _T("nang"), _T("wei"), _T("jian"), _T("nan"), _T("lun"), _T("hu"), _T("ling"), _T("you"), _T("yu"), _T("qing"), _T("yu"), _T("huan"), _T("wei"), _T("zhi"), _T("pei"), _T("tang"), _T("chou"), _T("ze"), _T("guo"), NULL};
const TCHAR* E1[] = {_T("wei"), _T("wo"), _T("man"), _T("zhang"), _T("fu"), _T("fan"), _T("ji"), _T("qi"), _T("qian"), _T("qi"), _T("qu"), _T("ya"), _T("xian"), _T("ao"), _T("cen"), _T("lan"), _T("ba"), _T("hu"), _T("ke"), _T("dong"), _T("jia"), _T("xiu"), _T("dai"), _T("gou"), _T("mao"), _T("min"), _T("yi"), _T("dong"), _T("jiao"), _T("xun"), _T("zheng"), _T("lao"), _T("lai"), _T("song"), _T("yan"), _T("gu"), _T("yao"), _T("guo"), _T("kong"), _T("jue"), _T("rong"), _T("yao"), _T("wai"), _T("zai"), _T("wei"), _T("yu"), _T("cuo"), _T("lou"), _T("zi"), _T("mei"), _T("sheng"), _T("song"), _T("ji"), _T("zhang"), _T("lin"), _T("deng"), _T("bin"), _T("yi"), _T("dian"), _T("chi"), _T("pang"), _T("cu"), _T("xun"), _T("yang"), _T("hou"), _T("lai"), _T("xi"), _T("chang"), _T("huang"), _T("yao"), _T("cheng"), _T("jiao"), _T("qu"), _T("shan"), _T("quan"), _T("qiu"), _T("an"), _T("guang"), _T("ma"), _T("niu"), _T("yun"), _T("xia"), _T("pao"), _T("fei"), _T("rong"), _T("kuai"), _T("shou"), _T("sun"), _T("bi"), _T("juan"), _T("li"), _T("yu"), _T("xian"), _T("yin"), NULL};
const TCHAR* E2[] = {_T("suan"), _T("yi"), _T("guo"), _T("luo"), _T("ni"), _T("she"), _T("cu"), _T("mi"), _T("hu"), _T("cha"), _T("wei"), _T("wei"), _T("mei"), _T("nao"), _T("zhang"), _T("jing"), _T("jue"), _T("liao"), _T("xie"), _T("xun"), _T("huan"), _T("chuan"), _T("huo"), _T("sun"), _T("yin"), _T("zhi"), _T("shi"), _T("tang"), _T("tun"), _T("xi"), _T("ren"), _T("yu"), _T("chi"), _T("yi"), _T("xiang"), _T("bo"), _T("yu"), _T("hun"), _T("cha"), _T("sou"), _T("mo"), _T("xiu"), _T("jin"), _T("san"), _T("zhuan"), _T("nang"), _T("pi"), _T("wu"), _T("gui"), _T("pao"), _T("xiu"), _T("xiang"), _T("tuo"), _T("an"), _T("yu"), _T("bi"), _T("geng"), _T("ao"), _T("jin"), _T("chan"), _T("xie"), _T("lin"), _T("ying"), _T("xin"), _T("dao"), _T("cun"), _T("chan"), _T("wu"), _T("zhi"), _T("ou"), _T("chong"), _T("wu"), _T("kai"), _T("chang"), _T("chuang"), _T("song"), _T("bian"), _T("niu"), _T("hu"), _T("chu"), _T("peng"), _T("da"), _T("yang"), _T("zuo"), _T("ni"), _T("fu"), _T("chao"), _T("yi"), _T("yi"), _T("tong"), _T("yan"), _T("ce"), _T("kai"), _T("xun"), NULL};
const TCHAR* E3[] = {_T("ke"), _T("yun"), _T("bei"), _T("song"), _T("qian"), _T("kui"), _T("kun"), _T("yi"), _T("ti"), _T("quan"), _T("qie"), _T("xing"), _T("fei"), _T("chang"), _T("wang"), _T("chou"), _T("hu"), _T("cui"), _T("yun"), _T("kui"), _T("e"), _T("leng"), _T("zhui"), _T("qiao"), _T("bi"), _T("su"), _T("qian"), _T("yong"), _T("jing"), _T("qiao"), _T("chong"), _T("chu"), _T("lin"), _T("meng"), _T("tian"), _T("hui"), _T("shuan"), _T("yan"), _T("wei"), _T("hong"), _T("min"), _T("kang"), _T("ta"), _T("lv"), _T("kun"), _T("jiu"), _T("lang"), _T("yu"), _T("chang"), _T("xi"), _T("wen"), _T("hun"), _T("yan"), _T("qu"), _T("que"), _T("he"), _T("tian"), _T("que"), _T("kan"), _T("pan"), _T("pan"), _T("qiang"), _T("shui"), _T("qi"), _T("si"), _T("cha"), _T("feng"), _T("yuan"), _T("mu"), _T("mian"), _T("dun"), _T("mi"), _T("gu"), _T("bian"), _T("wen"), _T("hang"), _T("wei"), _T("le"), _T("gan"), _T("shu"), _T("long"), _T("lu"), _T("yang"), _T("si"), _T("duo"), _T("ling"), _T("mao"), _T("luo"), _T("xuan"), _T("pan"), _T("tuo"), _T("hong"), _T("min"), _T("jing"), NULL};
const TCHAR* E4[] = {_T("huan"), _T("wei"), _T("lie"), _T("jia"), _T("zhen"), _T("yin"), _T("hui"), _T("zhu"), _T("ji"), _T("xu"), _T("hui"), _T("tao"), _T("xun"), _T("jiang"), _T("liu"), _T("hu"), _T("xun"), _T("ru"), _T("su"), _T("wu"), _T("lai"), _T("wei"), _T("zhuo"), _T("juan"), _T("cen"), _T("bang"), _T("xi"), _T("mei"), _T("huan"), _T("zhu"), _T("qi"), _T("xi"), _T("song"), _T("du"), _T("zhuo"), _T("pi"), _T("mian"), _T("gan"), _T("fei"), _T("cong"), _T("shen"), _T("guan"), _T("lu"), _T("shuan"), _T("xie"), _T("yan"), _T("mian"), _T("qiu"), _T("sou"), _T("huang"), _T("xu"), _T("pen"), _T("jian"), _T("xuan"), _T("wo"), _T("mei"), _T("yan"), _T("zhen"), _T("ke"), _T("she"), _T("mang"), _T("ying"), _T("pu"), _T("li"), _T("ru"), _T("ta"), _T("hun"), _T("bi"), _T("xiu"), _T("fu"), _T("tang"), _T("pang"), _T("ming"), _T("huang"), _T("ying"), _T("xiao"), _T("lan"), _T("cao"), _T("hu"), _T("luo"), _T("huan"), _T("lian"), _T("zhu"), _T("yi"), _T("lu"), _T("xuan"), _T("gan"), _T("shu"), _T("si"), _T("shan"), _T("shao"), _T("tong"), _T("chan"), _T("lai"), NULL};
const TCHAR* E5[] = {_T("sui"), _T("li"), _T("dan"), _T("chan"), _T("lian"), _T("ru"), _T("pu"), _T("bi"), _T("hao"), _T("zhuo"), _T("han"), _T("xie"), _T("ying"), _T("yue"), _T("fen"), _T("hao"), _T("ba"), _T("mian"), _T("gui"), _T("dang"), _T("mi"), _T("you"), _T("chen"), _T("ning"), _T("qian"), _T("qian"), _T("wu"), _T("liao"), _T("qian"), _T("huan"), _T("jian"), _T("jian"), _T("chuo"), _T("ya"), _T("wu"), _T("jiong"), _T("ze"), _T("yi"), _T("er"), _T("jia"), _T("jing"), _T("dai"), _T("hou"), _T("pang"), _T("bu"), _T("li"), _T("qiu"), _T("xiao"), _T("ti"), _T("qun"), _T("kui"), _T("wei"), _T("huan"), _T("lu"), _T("chuan"), _T("huang"), _T("qiu"), _T("xia"), _T("ao"), _T("gou"), _T("ta"), _T("liu"), _T("xian"), _T("lin"), _T("ju"), _T("xie"), _T("miao"), _T("sui"), _T("la"), _T("ji"), _T("hui"), _T("tuan"), _T("zhi"), _T("kao"), _T("zhi"), _T("ji"), _T("e"), _T("can"), _T("xi"), _T("ju"), _T("chan"), _T("jing"), _T("nu"), _T("mi"), _T("fu"), _T("bi"), _T("yu"), _T("che"), _T("shuo"), _T("fei"), _T("yan"), _T("wu"), _T("yu"), _T("bi"), NULL};
const TCHAR* E6[] = {_T("jin"), _T("zi"), _T("gui"), _T("niu"), _T("yu"), _T("si"), _T("da"), _T("zhou"), _T("shan"), _T("qie"), _T("ya"), _T("rao"), _T("shu"), _T("luan"), _T("jiao"), _T("pin"), _T("cha"), _T("li"), _T("ping"), _T("wa"), _T("xian"), _T("suo"), _T("di"), _T("wei"), _T("e"), _T("jing"), _T("biao"), _T("jie"), _T("chang"), _T("bi"), _T("chan"), _T("nu"), _T("ao"), _T("yuan"), _T("ting"), _T("wu"), _T("gou"), _T("mo"), _T("pi"), _T("ai"), _T("pin"), _T("chi"), _T("li"), _T("yan"), _T("qiang"), _T("piao"), _T("chang"), _T("lei"), _T("zhang"), _T("xi"), _T("shan"), _T("bi"), _T("niao"), _T("ma"), _T("shuang"), _T("ga"), _T("ga"), _T("fu"), _T("nu"), _T("zi"), _T("jie"), _T("jue"), _T("bao"), _T("zang"), _T("si"), _T("fu"), _T("zou"), _T("yi"), _T("nu"), _T("dai"), _T("xiao"), _T("hua"), _T("pian"), _T("li"), _T("qi"), _T("ke"), _T("zhui"), _T("can"), _T("zhi"), _T("wu"), _T("ao"), _T("liu"), _T("shan"), _T("biao"), _T("cong"), _T("zhan"), _T("ji"), _T("xiang"), _T("mi"), _T("yu"), _T("zhou"), _T("ge"), _T("wan"), _T("kuang"), NULL};
const TCHAR* E7[] = {_T("yun"), _T("pi"), _T("shu"), _T("gan"), _T("xie"), _T("fu"), _T("zhou"), _T("fu"), _T("chu"), _T("dai"), _T("ku"), _T("hang"), _T("jiang"), _T("geng"), _T("xiao"), _T("ti"), _T("ling"), _T("qi"), _T("fei"), _T("shang"), _T("gun"), _T("duo"), _T("shou"), _T("liu"), _T("quan"), _T("wan"), _T("zi"), _T("ke"), _T("xiang"), _T("ti"), _T("miao"), _T("hui"), _T("si"), _T("bian"), _T("gou"), _T("zhui"), _T("min"), _T("jin"), _T("zhen"), _T("ru"), _T("gao"), _T("li"), _T("yi"), _T("jian"), _T("bin"), _T("piao"), _T("man"), _T("lei"), _T("miao"), _T("sao"), _T("xie"), _T("liao"), _T("zeng"), _T("jiang"), _T("qian"), _T("qiao"), _T("huan"), _T("zuan"), _T("yao"), _T("ji"), _T("chuan"), _T("zai"), _T("yong"), _T("ding"), _T("ji"), _T("wei"), _T("bin"), _T("min"), _T("jue"), _T("ke"), _T("long"), _T("dian"), _T("dai"), _T("po"), _T("min"), _T("jia"), _T("er"), _T("gong"), _T("xu"), _T("ya"), _T("heng"), _T("yao"), _T("luo"), _T("xi"), _T("hun"), _T("lian"), _T("qi"), _T("ying"), _T("qi"), _T("hu"), _T("kun"), _T("yan"), _T("cong"), _T("wan"), NULL};
const TCHAR* E8[] = {_T("chen"), _T("ju"), _T("mao"), _T("yu"), _T("yuan"), _T("xia"), _T("nao"), _T("ai"), _T("tang"), _T("jin"), _T("huang"), _T("ying"), _T("cui"), _T("cong"), _T("xuan"), _T("zhang"), _T("pu"), _T("can"), _T("qu"), _T("lu"), _T("bi"), _T("zan"), _T("wen"), _T("wei"), _T("yun"), _T("tao"), _T("wu"), _T("biao"), _T("qi"), _T("cha"), _T("ma"), _T("li"), _T("pi"), _T("miao"), _T("yao"), _T("rui"), _T("jian"), _T("chu"), _T("cheng"), _T("cong"), _T("xiao"), _T("fang"), _T("pa"), _T("zhu"), _T("nai"), _T("zhi"), _T("zhe"), _T("long"), _T("jiu"), _T("ping"), _T("lu"), _T("xia"), _T("xiao"), _T("you"), _T("zhi"), _T("tuo"), _T("zhi"), _T("ling"), _T("gou"), _T("di"), _T("li"), _T("tuo"), _T("cheng"), _T("kao"), _T("lao"), _T("ya"), _T("rao"), _T("zhi"), _T("zhen"), _T("guang"), _T("qi"), _T("ting"), _T("gua"), _T("jiu"), _T("hua"), _T("heng"), _T("gui"), _T("jie"), _T("luan"), _T("juan"), _T("an"), _T("xu"), _T("fan"), _T("gu"), _T("fu"), _T("jue"), _T("zi"), _T("suo"), _T("ling"), _T("chu"), _T("fen"), _T("du"), _T("qian"), _T("zhao"), NULL};
const TCHAR* E9[] = {_T("luo"), _T("chui"), _T("liang"), _T("guo"), _T("jian"), _T("di"), _T("ju"), _T("cou"), _T("shen"), _T("nan"), _T("cha"), _T("lian"), _T("lan"), _T("ji"), _T("pin"), _T("ju"), _T("qiu"), _T("duan"), _T("chui"), _T("chen"), _T("lv"), _T("cha"), _T("ju"), _T("xuan"), _T("mei"), _T("ying"), _T("zhen"), _T("fei"), _T("ta"), _T("sun"), _T("xie"), _T("gao"), _T("cui"), _T("gao"), _T("shuo"), _T("bin"), _T("rong"), _T("zhu"), _T("xie"), _T("jin"), _T("qiang"), _T("qi"), _T("chu"), _T("tang"), _T("zhu"), _T("hu"), _T("gan"), _T("yue"), _T("qing"), _T("tuo"), _T("jue"), _T("qiao"), _T("qin"), _T("lu"), _T("zun"), _T("xi"), _T("ju"), _T("yuan"), _T("lei"), _T("yan"), _T("lin"), _T("bo"), _T("cha"), _T("you"), _T("ao"), _T("mo"), _T("cu"), _T("shang"), _T("tian"), _T("yun"), _T("lian"), _T("piao"), _T("dan"), _T("ji"), _T("bin"), _T("yi"), _T("ren"), _T("e"), _T("gu"), _T("ke"), _T("lu"), _T("zhi"), _T("yi"), _T("zhen"), _T("hu"), _T("li"), _T("yao"), _T("shi"), _T("zhi"), _T("quan"), _T("lu"), _T("zhe"), _T("nian"), _T("wang"), NULL};
const TCHAR* EA[] = {_T("chuo"), _T("zi"), _T("cou"), _T("lu"), _T("lin"), _T("wei"), _T("jian"), _T("qiang"), _T("jia"), _T("ji"), _T("ji"), _T("kan"), _T("deng"), _T("gai"), _T("jian"), _T("zang"), _T("ou"), _T("ling"), _T("bu"), _T("beng"), _T("zeng"), _T("pi"), _T("po"), _T("ga"), _T("la"), _T("gan"), _T("hao"), _T("tan"), _T("gao"), _T("ze"), _T("xin"), _T("yun"), _T("gui"), _T("he"), _T("zan"), _T("mao"), _T("yu"), _T("chang"), _T("ni"), _T("qi"), _T("sheng"), _T("ye"), _T("chao"), _T("yan"), _T("hui"), _T("bu"), _T("han"), _T("gui"), _T("xuan"), _T("kui"), _T("ai"), _T("ming"), _T("tun"), _T("xun"), _T("yao"), _T("xi"), _T("nang"), _T("ban"), _T("shi"), _T("kuang"), _T("yi"), _T("zhi"), _T("zi"), _T("gai"), _T("jin"), _T("zhen"), _T("lai"), _T("qiu"), _T("ji"), _T("dan"), _T("fu"), _T("chan"), _T("ji"), _T("xi"), _T("di"), _T("yu"), _T("gou"), _T("jin"), _T("qu"), _T("jian"), _T("jiang"), _T("pin"), _T("mao"), _T("gu"), _T("wu"), _T("gu"), _T("ji"), _T("ju"), _T("jian"), _T("pian"), _T("kao"), _T("qie"), _T("suo"), _T("bai"), NULL};
const TCHAR* EB[] = {_T("ge"), _T("bo"), _T("mao"), _T("mu"), _T("cui"), _T("jian"), _T("san"), _T("shu"), _T("chang"), _T("lu"), _T("pu"), _T("qu"), _T("pie"), _T("dao"), _T("xian"), _T("chuan"), _T("dong"), _T("ya"), _T("yin"), _T("ke"), _T("yun"), _T("po"), _T("chi"), _T("jiao"), _T("du"), _T("die"), _T("you"), _T("yuan"), _T("guo"), _T("yue"), _T("wo"), _T("rong"), _T("huang"), _T("jing"), _T("ruan"), _T("tai"), _T("gong"), _T("zhun"), _T("na"), _T("yao"), _T("qian"), _T("long"), _T("dong"), _T("ka"), _T("lu"), _T("jia"), _T("shen"), _T("zhou"), _T("zuo"), _T("gua"), _T("zhen"), _T("qu"), _T("zhi"), _T("jing"), _T("guang"), _T("dong"), _T("yan"), _T("kuai"), _T("sa"), _T("gai"), _T("pian"), _T("zhen"), _T("mi"), _T("tun"), _T("luo"), _T("cuo"), _T("pao"), _T("wan"), _T("niao"), _T("jing"), _T("a"), _T("fei"), _T("yu"), _T("zong"), _T("ding"), _T("jian"), _T("cou"), _T("nan"), _T("mian"), _T("wa"), _T("e"), _T("shu"), _T("cheng"), _T("ying"), _T("ge"), _T("lv"), _T("bin"), _T("teng"), _T("zhi"), _T("chuai"), _T("gu"), _T("meng"), _T("sao"), _T("shan"), NULL};
const TCHAR* EC[] = {_T("lian"), _T("lin"), _T("yu"), _T("xi"), _T("qi"), _T("sha"), _T("xin"), _T("she"), _T("biao"), _T("sa"), _T("ju"), _T("sou"), _T("biao"), _T("biao"), _T("shu"), _T("gou"), _T("gu"), _T("hu"), _T("fei"), _T("ji"), _T("lan"), _T("wu"), _T("pei"), _T("mao"), _T("zhan"), _T("jing"), _T("ni"), _T("liu"), _T("yi"), _T("yang"), _T("wei"), _T("dun"), _T("qiang"), _T("shi"), _T("hu"), _T("zhu"), _T("xuan"), _T("tai"), _T("ye"), _T("yang"), _T("wu"), _T("han"), _T("men"), _T("zhuo"), _T("yan"), _T("hu"), _T("yu"), _T("wei"), _T("duan"), _T("bao"), _T("xuan"), _T("bian"), _T("tui"), _T("liu"), _T("man"), _T("shang"), _T("yu"), _T("yi"), _T("yu"), _T("fan"), _T("sui"), _T("xian"), _T("jue"), _T("cuan"), _T("biao"), _T("dao"), _T("xu"), _T("xi"), _T("li"), _T("hu"), _T("jiong"), _T("hu"), _T("fei"), _T("shi"), _T("si"), _T("xian"), _T("zhi"), _T("qu"), _T("hu"), _T("fu"), _T("zuo"), _T("mi"), _T("zhi"), _T("ci"), _T("zhen"), _T("tiao"), _T("qi"), _T("chan"), _T("xi"), _T("zhuo"), _T("xi"), _T("rang"), _T("te"), _T("tan"), NULL};
const TCHAR* ED[] = {_T("dui"), _T("jia"), _T("hui"), _T("nv"), _T("nen"), _T("yang"), _T("zi"), _T("que"), _T("qian"), _T("min"), _T("ni"), _T("qi"), _T("dui"), _T("mao"), _T("men"), _T("gang"), _T("yu"), _T("yu"), _T("da"), _T("xue"), _T("miao"), _T("ji"), _T("gan"), _T("dang"), _T("hua"), _T("che"), _T("dun"), _T("ya"), _T("zhuo"), _T("bian"), _T("feng"), _T("fa"), _T("ai"), _T("li"), _T("long"), _T("zha"), _T("tong"), _T("di"), _T("la"), _T("tuo"), _T("fei"), _T("xing"), _T("mang"), _T("xia"), _T("qiao"), _T("zhai"), _T("dong"), _T("nao"), _T("luo"), _T("wo"), _T("qi"), _T("dui"), _T("bei"), _T("ding"), _T("chen"), _T("zhou"), _T("jie"), _T("di"), _T("xuan"), _T("bian"), _T("zhe"), _T("gun"), _T("sang"), _T("qing"), _T("qu"), _T("dun"), _T("deng"), _T("jiang"), _T("ca"), _T("meng"), _T("bo"), _T("kan"), _T("zhi"), _T("fu"), _T("fu"), _T("xu"), _T("mian"), _T("kou"), _T("dun"), _T("miao"), _T("dan"), _T("sheng"), _T("yuan"), _T("yi"), _T("sui"), _T("zi"), _T("chi"), _T("mou"), _T("lai"), _T("jian"), _T("di"), _T("suo"), _T("ya"), _T("ni"), NULL};
const TCHAR* EE[] = {_T("sui"), _T("pi"), _T("rui"), _T("sou"), _T("kui"), _T("mao"), _T("ke"), _T("ming"), _T("piao"), _T("cheng"), _T("kan"), _T("lin"), _T("gu"), _T("ding"), _T("bi"), _T("quan"), _T("tian"), _T("fan"), _T("zhen"), _T("she"), _T("wan"), _T("tuan"), _T("fu"), _T("gang"), _T("gu"), _T("li"), _T("yan"), _T("pi"), _T("lan"), _T("li"), _T("ji"), _T("zeng"), _T("he"), _T("guan"), _T("juan"), _T("jin"), _T("ga"), _T("yi"), _T("po"), _T("zhao"), _T("liao"), _T("tu"), _T("chuan"), _T("shan"), _T("men"), _T("chai"), _T("nv"), _T("bu"), _T("tai"), _T("ju"), _T("ban"), _T("qian"), _T("fang"), _T("kang"), _T("tou"), _T("huo"), _T("ba"), _T("yu"), _T("zheng"), _T("gu"), _T("ke"), _T("po"), _T("bu"), _T("bo"), _T("yue"), _T("mu"), _T("tan"), _T("dian"), _T("shuo"), _T("shi"), _T("xuan"), _T("she"), _T("bi"), _T("ni"), _T("pi"), _T("duo"), _T("kao"), _T("lao"), _T("er"), _T("you"), _T("cheng"), _T("jia"), _T("nao"), _T("ye"), _T("cheng"), _T("diao"), _T("yin"), _T("kai"), _T("zhu"), _T("ding"), _T("diu"), _T("hua"), _T("quan"), _T("ge"), NULL};
const TCHAR* EF[] = {_T("sha"), _T("diao"), _T("zheng"), _T("se"), _T("chong"), _T("tang"), _T("an"), _T("ru"), _T("lao"), _T("lai"), _T("te"), _T("keng"), _T("zeng"), _T("li"), _T("gao"), _T("e"), _T("cuo"), _T("lve"), _T("liu"), _T("kai"), _T("jian"), _T("lang"), _T("qin"), _T("ju"), _T("a"), _T("qing"), _T("nuo"), _T("ben"), _T("de"), _T("guo"), _T("kun"), _T("gu"), _T("huo"), _T("pei"), _T("juan"), _T("tan"), _T("zi"), _T("qie"), _T("jie"), _T("si"), _T("e"), _T("cha"), _T("sou"), _T("huan"), _T("ai"), _T("lou"), _T("qiang"), _T("fei"), _T("mei"), _T("mo"), _T("ge"), _T("juan"), _T("na"), _T("liu"), _T("yi"), _T("jia"), _T("bin"), _T("biao"), _T("tang"), _T("man"), _T("luo"), _T("yong"), _T("zu"), _T("xuan"), _T("di"), _T("chan"), _T("jue"), _T("pu"), _T("lu"), _T("dun"), _T("lan"), _T("pu"), _T("cuan"), _T("qiang"), _T("deng"), _T("huo"), _T("shu"), _T("yi"), _T("cha"), _T("biao"), _T("zhong"), _T("shen"), _T("cuo"), _T("zhi"), _T("bi"), _T("zi"), _T("mo"), _T("shu"), _T("lv"), _T("ji"), _T("fu"), _T("lang"), _T("ke"), _T("ren"), NULL};
const TCHAR* F0[] = {_T("zhen"), _T("ji"), _T("se"), _T("nian"), _T("fu"), _T("rang"), _T("gui"), _T("jiao"), _T("hao"), _T("xi"), _T("po"), _T("die"), _T("hu"), _T("yong"), _T("jiu"), _T("yuan"), _T("bao"), _T("zhen"), _T("gu"), _T("dong"), _T("lu"), _T("qu"), _T("chi"), _T("si"), _T("er"), _T("zhi"), _T("gua"), _T("xiu"), _T("luan"), _T("bo"), _T("li"), _T("gu"), _T("yu"), _T("xian"), _T("ti"), _T("wu"), _T("miao"), _T("an"), _T("bei"), _T("chun"), _T("hu"), _T("e"), _T("ci"), _T("mei"), _T("wu"), _T("yao"), _T("jian"), _T("ying"), _T("zhe"), _T("liu"), _T("liao"), _T("jiao"), _T("jiu"), _T("yu"), _T("hu"), _T("lu"), _T("guan"), _T("chuang"), _T("ding"), _T("jie"), _T("li"), _T("shan"), _T("li"), _T("you"), _T("gan"), _T("ke"), _T("da"), _T("zha"), _T("pao"), _T("zhu"), _T("xian"), _T("jia"), _T("ya"), _T("yi"), _T("zhi"), _T("lao"), _T("wu"), _T("cuo"), _T("xian"), _T("sha"), _T("zhu"), _T("fei"), _T("gu"), _T("wei"), _T("yu"), _T("yu"), _T("dan"), _T("la"), _T("yi"), _T("hou"), _T("chai"), _T("lou"), _T("jia"), _T("sao"), NULL};
const TCHAR* F1[] = {_T("chi"), _T("mo"), _T("ban"), _T("ji"), _T("huang"), _T("biao"), _T("luo"), _T("ying"), _T("zhai"), _T("long"), _T("yin"), _T("chou"), _T("ban"), _T("lai"), _T("yi"), _T("dian"), _T("pi"), _T("dian"), _T("qu"), _T("yi"), _T("song"), _T("xi"), _T("qiong"), _T("zhun"), _T("bian"), _T("yao"), _T("tiao"), _T("dou"), _T("ke"), _T("yu"), _T("xun"), _T("ju"), _T("yu"), _T("yi"), _T("cha"), _T("na"), _T("ren"), _T("jin"), _T("mei"), _T("pan"), _T("dang"), _T("jia"), _T("ge"), _T("ken"), _T("lian"), _T("cheng"), _T("lian"), _T("jian"), _T("biao"), _T("chu"), _T("ti"), _T("bi"), _T("ju"), _T("duo"), _T("da"), _T("bei"), _T("bao"), _T("lv"), _T("bian"), _T("lan"), _T("chi"), _T("zhe"), _T("qiang"), _T("ru"), _T("pan"), _T("pi"), _T("xu"), _T("jun"), _T("cun"), _T("jin"), _T("lei"), _T("zi"), _T("chao"), _T("si"), _T("huo"), _T("lao"), _T("tang"), _T("ou"), _T("lou"), _T("jiang"), _T("nou"), _T("mo"), _T("die"), _T("ding"), _T("dan"), _T("ling"), _T("ning"), _T("guo"), _T("kui"), _T("ao"), _T("qin"), _T("han"), _T("qi"), _T("hang"), NULL};
const TCHAR* F2[] = {_T("jie"), _T("he"), _T("ying"), _T("ke"), _T("han"), _T("e"), _T("zhuan"), _T("nie"), _T("man"), _T("sang"), _T("hao"), _T("ru"), _T("pin"), _T("hu"), _T("qian"), _T("qiu"), _T("ji"), _T("chai"), _T("hui"), _T("ge"), _T("meng"), _T("fu"), _T("pi"), _T("rui"), _T("xian"), _T("hao"), _T("jie"), _T("gong"), _T("dou"), _T("yin"), _T("chi"), _T("han"), _T("gu"), _T("he"), _T("li"), _T("you"), _T("ran"), _T("zha"), _T("qiu"), _T("ling"), _T("cheng"), _T("you"), _T("qiong"), _T("jia"), _T("nao"), _T("zhi"), _T("si"), _T("qu"), _T("ting"), _T("kuo"), _T("qi"), _T("jiao"), _T("yang"), _T("mou"), _T("shen"), _T("zhe"), _T("shao"), _T("wu"), _T("li"), _T("chu"), _T("fu"), _T("qiang"), _T("qing"), _T("qi"), _T("xi"), _T("yu"), _T("fei"), _T("guo"), _T("guo"), _T("yi"), _T("pi"), _T("tiao"), _T("quan"), _T("wan"), _T("lang"), _T("meng"), _T("chun"), _T("rong"), _T("nan"), _T("fu"), _T("kui"), _T("ke"), _T("fu"), _T("sou"), _T("yu"), _T("you"), _T("lou"), _T("qiu"), _T("bian"), _T("mao"), _T("qin"), _T("ao"), _T("man"), _T("mang"), NULL};
const TCHAR* F3[] = {_T("ma"), _T("yuan"), _T("xi"), _T("chi"), _T("tang"), _T("pang"), _T("shi"), _T("huang"), _T("cao"), _T("piao"), _T("tang"), _T("xi"), _T("xiang"), _T("zhong"), _T("zhang"), _T("shuai"), _T("mao"), _T("peng"), _T("hui"), _T("pan"), _T("shan"), _T("huo"), _T("meng"), _T("chan"), _T("lian"), _T("mie"), _T("li"), _T("du"), _T("qu"), _T("fou"), _T("ying"), _T("qing"), _T("xia"), _T("shi"), _T("zhu"), _T("yu"), _T("ji"), _T("du"), _T("ji"), _T("jian"), _T("zhao"), _T("zi"), _T("hu"), _T("qiong"), _T("po"), _T("da"), _T("sheng"), _T("ze"), _T("gou"), _T("li"), _T("si"), _T("tiao"), _T("jia"), _T("bian"), _T("chi"), _T("kou"), _T("bi"), _T("xian"), _T("yan"), _T("quan"), _T("zheng"), _T("jun"), _T("shi"), _T("gang"), _T("pa"), _T("shao"), _T("xiao"), _T("qing"), _T("ze"), _T("qie"), _T("zhu"), _T("ruo"), _T("qian"), _T("tuo"), _T("bi"), _T("dan"), _T("kong"), _T("yuan"), _T("xiao"), _T("zhen"), _T("kui"), _T("huang"), _T("hou"), _T("gou"), _T("fei"), _T("li"), _T("bi"), _T("chi"), _T("su"), _T("mie"), _T("dou"), _T("lu"), _T("duan"), _T("gui"), NULL};
const TCHAR* F4[] = {_T("dian"), _T("zan"), _T("deng"), _T("bo"), _T("lai"), _T("zhou"), _T("yu"), _T("yu"), _T("chong"), _T("xi"), _T("nie"), _T("nv"), _T("chuan"), _T("shan"), _T("yi"), _T("bi"), _T("zhong"), _T("ban"), _T("fang"), _T("ge"), _T("lu"), _T("zhu"), _T("ze"), _T("xi"), _T("shao"), _T("wei"), _T("meng"), _T("shou"), _T("cao"), _T("chong"), _T("meng"), _T("qin"), _T("niao"), _T("jia"), _T("qiu"), _T("sha"), _T("bi"), _T("di"), _T("qian"), _T("suo"), _T("jie"), _T("tang"), _T("xi"), _T("xian"), _T("mi"), _T("ba"), _T("li"), _T("tiao"), _T("xi"), _T("ci"), _T("can"), _T("lin"), _T("zong"), _T("san"), _T("hou"), _T("zan"), _T("ci"), _T("xu"), _T("rou"), _T("qiu"), _T("jiang"), _T("gen"), _T("ji"), _T("yi"), _T("ling"), _T("xi"), _T("zhu"), _T("fei"), _T("jian"), _T("pian"), _T("he"), _T("yi"), _T("mi"), _T("zhi"), _T("qi"), _T("qi"), _T("yao"), _T("dao"), _T("fu"), _T("qu"), _T("jiu"), _T("ju"), _T("lie"), _T("zi"), _T("zan"), _T("nan"), _T("zhe"), _T("jiang"), _T("chi"), _T("ding"), _T("gan"), _T("zhou"), _T("yi"), _T("gu"), NULL};
const TCHAR* F5[] = {_T("cu"), _T("tuo"), _T("xian"), _T("ming"), _T("zhi"), _T("yan"), _T("shi"), _T("cheng"), _T("tu"), _T("lei"), _T("kun"), _T("pei"), _T("hu"), _T("ti"), _T("xu"), _T("hai"), _T("tang"), _T("lao"), _T("bu"), _T("jiao"), _T("xi"), _T("ju"), _T("li"), _T("xun"), _T("shi"), _T("cuo"), _T("dun"), _T("qiong"), _T("xue"), _T("cu"), _T("bie"), _T("bao"), _T("ta"), _T("jian"), _T("fu"), _T("qiang"), _T("zhi"), _T("fu"), _T("shan"), _T("li"), _T("tuo"), _T("jia"), _T("bo"), _T("tai"), _T("kui"), _T("qiao"), _T("bi"), _T("xian"), _T("xian"), _T("ji"), _T("jiao"), _T("liang"), _T("ji"), _T("chuo"), _T("huai"), _T("chi"), _T("zhi"), _T("dian"), _T("bo"), _T("zhi"), _T("jian"), _T("die"), _T("chuai"), _T("zhong"), _T("ju"), _T("duo"), _T("cuo"), _T("pian"), _T("rou"), _T("nie"), _T("pan"), _T("qi"), _T("chu"), _T("jue"), _T("pu"), _T("fan"), _T("cu"), _T("zhu"), _T("lin"), _T("chan"), _T("lie"), _T("cuo"), _T("xie"), _T("zhi"), _T("diao"), _T("mo"), _T("xiu"), _T("mo"), _T("pi"), _T("hu"), _T("jue"), _T("shang"), _T("gu"), _T("zi"), NULL};
const TCHAR* F6[] = {_T("gong"), _T("su"), _T("zhi"), _T("zi"), _T("qing"), _T("jing"), _T("yu"), _T("li"), _T("wen"), _T("ting"), _T("ji"), _T("pei"), _T("fei"), _T("sha"), _T("yin"), _T("ai"), _T("xian"), _T("mai"), _T("chen"), _T("ju"), _T("bao"), _T("tiao"), _T("chai"), _T("yin"), _T("yu"), _T("chuo"), _T("wo"), _T("min"), _T("yuan"), _T("tuo"), _T("cui"), _T("sun"), _T("juan"), _T("ju"), _T("luo"), _T("ju"), _T("chou"), _T("qiong"), _T("luan"), _T("wu"), _T("zan"), _T("mou"), _T("ao"), _T("liu"), _T("bei"), _T("xin"), _T("you"), _T("fang"), _T("ba"), _T("ping"), _T("nian"), _T("lu"), _T("su"), _T("fu"), _T("hou"), _T("tai"), _T("gui"), _T("jie"), _T("wei"), _T("er"), _T("ji"), _T("jiao"), _T("xiang"), _T("xun"), _T("geng"), _T("li"), _T("lian"), _T("jian"), _T("shi"), _T("tiao"), _T("gun"), _T("sha"), _T("huan"), _T("ji"), _T("qing"), _T("ling"), _T("zou"), _T("fei"), _T("kun"), _T("chang"), _T("gu"), _T("ni"), _T("nian"), _T("diao"), _T("shi"), _T("zi"), _T("fen"), _T("die"), _T("e"), _T("qiu"), _T("fu"), _T("huang"), _T("bian"), _T("sao"), NULL};
const TCHAR* F7[] = {_T("ao"), _T("qi"), _T("ta"), _T("guan"), _T("yao"), _T("le"), _T("biao"), _T("xue"), _T("man"), _T("min"), _T("yong"), _T("gui"), _T("shan"), _T("zun"), _T("li"), _T("da"), _T("yang"), _T("da"), _T("qiao"), _T("man"), _T("jian"), _T("ju"), _T("rou"), _T("gou"), _T("bei"), _T("jie"), _T("tou"), _T("ku"), _T("gu"), _T("di"), _T("hou"), _T("ge"), _T("ke"), _T("bi"), _T("lou"), _T("qia"), _T("kuan"), _T("bin"), _T("du"), _T("mei"), _T("ba"), _T("yan"), _T("liang"), _T("xiao"), _T("wang"), _T("chi"), _T("xiang"), _T("yan"), _T("tie"), _T("tao"), _T("yong"), _T("biao"), _T("kun"), _T("mao"), _T("ran"), _T("tiao"), _T("ji"), _T("zi"), _T("xiu"), _T("quan"), _T("jiu"), _T("bin"), _T("huan"), _T("lie"), _T("mo"), _T("hui"), _T("mi"), _T("ji"), _T("jun"), _T("zhu"), _T("mi"), _T("qi"), _T("ao"), _T("she"), _T("lin"), _T("dai"), _T("chu"), _T("you"), _T("xia"), _T("yi"), _T("qu"), _T("du"), _T("li"), _T("qing"), _T("can"), _T("an"), _T("fen"), _T("you"), _T("wu"), _T("yan"), _T("xi"), _T("qui"), _T("han"), NULL};


const TCHAR** py_entries[] = {
	B0, B1, B2, B3, B4, B5, B6, B7, B8, B9, BA, BB, BC, BD, BE, BF,
	C0, C1, C2, C3, C4, C5, C6, C7, C8, C9, CA, CB, CC, CD, CE, CF,
	D0, D1, D2, D3, D4, D5, D6, D7, D8, D9, DA, DB, DC, DD, DE, DF,
	E0, E1, E2, E3, E4, E5, E6, E7, E8, E9, EA, EB, EC, ED, EE, EF,
	F0, F1, F2, F3, F4, F5, F6, F7
};

typedef unsigned char uchar;

const TCHAR* py_lookup(uchar index, uchar order)
{
	if (index < 0xB0 || index > 0xF7)
		return NULL;

	if (order < 0xA1 || order > 0xFE)
		return NULL;

	int offset = index - 0xB0;
	const TCHAR** pEntry = py_entries[offset];

	//get entry length
	uchar entryLen = 0;
	int i = 0;
	const TCHAR* val = pEntry[i];
	while (val != NULL)
	{
		++entryLen;
		val = pEntry[++i];
	}

	int offsetInEntry = order - 0xA1;
	if (offsetInEntry + 1 <= entryLen)
	{
		return pEntry[offsetInEntry];
	}
	else
	{
		return NULL;
	}
}

NSString *py_lookup(NSString* strContent)
{
	
	NSString *strPinyin = [[[NSString alloc] init] autorelease];
	
	int nChars = [strContent length];
	for (int i = 0; i <nChars; ++i)
	{
		unichar ch = [strContent characterAtIndex: i];
		
		NSString *strChar = [NSString stringWithFormat: @"%C", ch];
		
		if (ch >= 0x4e00 && ch <= 0x9fa5) //这个范围内的字符是中文
		{
			std::string strGbkChar = NSStr2CStr(strChar);
			if (strGbkChar.length() == 2)
			{
				const TCHAR* result = py_lookup(strGbkChar[0], strGbkChar[1]);
				if (result == NULL)
				{
					strPinyin = [strPinyin stringByAppendingString:strChar];
				}
				else
				{
					NSString *strCharPinYin = CStr2NSStr(result);
					strPinyin = [strPinyin stringByAppendingString:strCharPinYin];
				}
			}
			else
			{
				strPinyin = [strPinyin stringByAppendingString:strChar];
			}
		}
		else
		{
			strPinyin = [strPinyin stringByAppendingString:strChar];
		}
	}
		
	return strPinyin;
}